(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');ga('create', 'UA-92920347-1', 'auto');ga('send', 'pageview');
$.browser={};$.browser.mozilla=/mozilla/.test(navigator.userAgent.toLowerCase())&&!/webkit/.test(navigator.userAgent.toLowerCase());$.browser.webkit=/webkit/.test(navigator.userAgent.toLowerCase());$.browser.opera=/opera/.test(navigator.userAgent.toLowerCase());$.browser.msie=/msie/.test(navigator.userAgent.toLowerCase())
var fg=0
function validateEmail(email){var re=/\S+@\S+\.\S+/;return re.test(email)}
function passwordCheck(str){$.post("/online/ajax.php",{data:$("#pass_str").data("tpl"),nick:$("#name_str").val(),pswd:str},function(r){if(r=='0'){$("#valid_name").html('<span style="color:lightsalmon"><i class="fas fa-times" /> неверный пароль</span>');fg=setTimeout(function(){$("#forget").show()},17000)}else if(r=='1'){$("#valid_name").html('<span style="color:lightgreen"><i class="fas fa-check" /> добро пожаловать!</span>');$("#l_form").submit()}else if(r=='2'){$("#valid_name").html('<span style="color:lightgreen"><i class="fas fa-check" /> пароль выслан</span>')}})}
function emailCheck(str){$.post("/online/ajax.php",{data:$("#name_str").data("tpl"),nick:str,email:str},function(r){if(r=='0')$("#valid_name").html('<span style="color:lightsalmon"><i class="fas fa-times" /> такой e-mail не найден</span>');else{str=$("#pass_str").val();if(str.length)passwordCheck(str);else $("#valid_name").html('<span style="color:lightblue;cursor:pointer" onClick="tokenSend(); return false" title="Вам будет выслана ссылка для входа"><i class="fas fa-check" /> войти без пароля?</span>')}})}
function nicknameCheck(str){$.post("/online/ajax.php",{data:$("#name_str").data("tpl"),nick:str,email:""},function(r){if(r=='0')$("#valid_name").html('<span style="color:lightsalmon"><i class="fas fa-times" /> имя/e-mail не найдены</span>');else{str=$("#pass_str").val();if(str.length)passwordCheck(str);else $("#valid_name").html('<span style="color:lightgreen"><i class="fas fa-check" /> теперь введите пароль</span>')}})}
function tokenSend(){$.post("/online/ajax.php",{data:$("#l_form").data("tpl"),nick:$("#name_str").val()},function(r){if(r=='1')$("#valid_name").html('<span style="color:lightgreen"><i class="fas fa-check" /> проверьте вашу почту</span>');else $("#valid_name").html('<span style="color:lightsalmon"><i class="fas fa-times" /> не удалось отправить</span>')})}
function newPassword(){return true}
$(document).ready(function(){
if($(".rightbar-header").data("log")=="out")history.pushState(null,"", "/")
$("#sidebarCollapse").on("click",function(){$("#sidebar").toggleClass("active");$("#sidebar").toggleClass("collapsed");$(this).toggleClass("active");$(this).toggleClass("collapsed")});
$("#rightbarCollapse").on("click",function(){$("#rightbar").toggleClass("active");$(this).toggleClass("active");if($("#rightbarIconUser").is(":hidden")){$("#rightbarIconUser").show();$("#rightbarIconUserX").hide()}else if($("#rightbarIconUserX").is(":hidden")){$("#rightbarIconUser").hide();$("#rightbarIconUserX").show()}});
$("a[name=modal]").click(function(e){e.preventDefault();$(".overlay").fadeTo("fast",0.65);$("#mwin").adClass("popup-show")});
$(".popup .close,.overlay").click(function(e){e.preventDefault();$(".overlay").hide();$("#mwin").removeClass("popup-show")});
$("#name_str").blur(function(){if(!$("#name_str").is(":hover")){str=$(this).val();if(str.length<2)$("#valid_name").html('<span style="color:pink"><i class="fas fa-times"></i> введите хотя бы 2 буквы</span>');else if(validateEmail(str)) emailCheck(str);else nicknameCheck(str)}})
$("#pass_str").keyup(function(){if($("#pass_str").is(":focus")){clearTimeout(fg);str=$(this).val();if(str.length)passwordCheck(str);else{str=$("#name_str").val();if(validateEmail(str))emailCheck(str);else $("#valid_name").html('<span style="color:lightgreen"><i class="fas fa-check" /> теперь введите пароль</span>')}}})
$(window).scroll(function(){if($(this).scrollTop()>100)$(".scrollToTop").fadeIn();else $(".scrollToTop").fadeOut()});
$(".scrollToTop").click(function(){$("html,body").animate({scrollTop:0},400);return false});
var cke_config={language:"ru"},editable=null
$("#editIcon").click(function(){$("#saveIcon").show();$("#editIcon").hide();if($("#editable").hasClass("monospace"))$("div#editable").replaceWith('<textarea id="editable" class="monospace" style="width:100%;height:'+$("#editable").html().split("\n").length+'em">'+$("#editable").html()+"</textarea>");else InlineEditor.create(document.querySelector("#editable"),cke_config).then(function(editor){editable=editor;$("#editable").click().focus()})})
$("#saveIcon").click(function(){$("#editIcon").show();$("#saveIcon").hide();if($("#editable").hasClass("monospace"))$("textarea#editable").replaceWith('<div id="editable" class="monospace">'+$("#editable").val()+"</div>");else editable.destroy();$.post("/online/ajax.php",{data:$("#saveIcon").data("tpl"),text:encodeURIComponent($("#editable").html())},function(r){})})
})
