<?php $cnames = array(
'Czechia' => 'Czech Republic',
'United States' => 'USA',
'Ireland' => 'Republic of Ireland',
'Macedonia' => 'FYR Macedonia',
'South Korea' => 'Korea Republic',
'China' => 'China PR',
'North Korea' => 'Korea DPR',
'Democratic Republic of Congo' => 'Congo DR',
'Cape Verde' => 'Cape Verde Islands',
'Saint Lucia' => 'St. Lucia',
'Turks and Caicos' => 'Turks and Caicos Islands',
'Surinam' => 'Suriname',
'Saint Kitts and Nevis' => 'St. Kitts and Nevis',
'Brunei' => 'Brunei Darussalam',
'Macao' => 'Macau',
'Taiwan' => 'Chinese Taipei',
'East Timor' => 'Timor-Leste',
'Saint Vincent and the Grenadines' => 'St. Vincent / Grenadines',
'Ivory Coast' => "Côte d'Ivoire",
"Cote d'Ivoire" => "Côte d'Ivoire",
'Eastern Samoa' => 'American Samoa',
);
//'Bosnia and Herzegovina' => 'Bosnia-Herzegovina',
?>
