<?php $groups = array(
'ENGLAND#PR' => 'England: Premier League',
'ENGLAND#EPL' => 'England: Premier League',
'ENGLAND#ECH' => 'England: Championship',
'ENGLAND#5R' => 'England: FA Cup',
'ENGLAND#4R' => 'England: FA Cup',
'ENGLAND#3R' => 'England: FA Cup',
'ENGLAND#QF' => 'England: FA Cup',
'ENGLAND#SF' => 'England: FA Cup',
'ENGLAND#CFINAL' => 'England: FA Cup',
'ENGLAND#CS' => 'England: Community Shield',
'ENGLAND#FINAL' => 'England: Championship Playoff',

'GERMANY#BL' => 'Germany: 1. Bundesliga',
'GERMANY#R16' => 'Germany: DFB Pokal',
'GERMANY#2R' => 'Germany: DFB Pokal',
'GERMANY#QF' => 'Germany: DFB Pokal',
'GERMANY#SF' => 'Germany: DFB Pokal',
'GERMANY#FINAL' => 'Germany: DFB Pokal',
'GERMANY#BPO' => 'Germany: 1. Bundesliga qualification',
'GERMANY#RPO' => 'Germany: 1. Bundesliga Play-offs',
'GERMANY#SC' => 'Germany: German Super Cup',

'ITALY#A' => 'Italy: Serie A',
'ITALY#R16' => 'Italy: Coppa Italia',
'ITALY#4R' => 'Italy: Coppa Italia',
'ITALY#QF' => 'Italy: Coppa Italia',
'ITALY#SF' => 'Italy: Coppa Italia',
'ITALY#FINAL' => 'Italy: Coppa Italia',
'ITALY#BPO' => 'Italy: Serie A/B Playoff',
'ITALY#SC' => 'Italy: Super Cup',

'FRANCE#L1' => 'France: Ligue 1',
'FRANCE#R32' => 'France: FA Cup',
'FRANCE#R16' => 'France: FA Cup',
'FRANCE#3R' => 'France: FA Cup',
'FRANCE#QF' => 'France: FA Cup',
'FRANCE#SF' => 'France: FA Cup',
'FRANCE#FINAL' => 'France: FA Cup',
'FRANCE#SC' => 'France: SuperCup',

'SPAIN#PD' => 'Spain: LaLiga',
'SPAIN#POSF' => 'Spain: Segunda Play-Offs',
'SPAIN#R32' => 'Spain: Copa del Rey',
'SPAIN#R16' => 'Spain: Copa del Rey',
'SPAIN#QF' => 'Spain: Copa del Rey',
'SPAIN#SF' => 'Spain: Copa del Rey',
'SPAIN#FINAL' => 'Spain: Copa del Rey',
'SPAIN#SC' => 'Spain: Supercup',

'SCOTLAND#PR' => 'Scotland: Premier League',
'SCOTLAND#SPL' => 'Scotland: Premier League',
'SCOTLAND#4R' => 'Scotland: Tennents Scottish Cup',
'SCOTLAND#5R' => 'Scotland: Tennents Scottish Cup',
'SCOTLAND#QF' => 'Scotland: Tennents Scottish Cup',
'SCOTLAND#SF' => 'Scotland: Tennents Scottish Cup',
'SCOTLAND#FINAL' => 'Scotland: Tennents Scottish Cup',

'NETHERLANDS#ERD' => 'Netherlands: Eredivisie',
'NETHERLANDS#2R' => 'Netherlands: KNVB Cup',
'NETHERLANDS#QF' => 'Netherlands: KNVB Cup',
'NETHERLANDS#SF' => 'Netherlands: KNVB Cup',
'NETHERLANDS#FINAL' => 'Netherlands: KNVB Cup',
'NETHERLANDS#SC' => 'Netherlands: Super Cup',

'PORTUGAL#PL' => 'Portugal: Primeira Liga',
'PORTUGAL#3R' => 'Portugal: Cup',
'PORTUGAL#4R' => 'Portugal: Cup',
'PORTUGAL#R16' => 'Portugal: Cup',
'PORTUGAL#QF' => 'Portugal: Cup',
'PORTUGAL#SF' => 'Portugal: Cup',
'PORTUGAL#FINAL' => 'Portugal: Cup',
'828953' => 'Portugal: League Cup',
'PORTUGAL#SC' => 'Portugal: Super Cup',

'RUSSIA#PR' => 'Россия: Премьер-Лига',
'RUSSIA#RFPL' => 'Россия: Премьер-Лига',
'RUSSIA#FNL' => 'Russia: FNL',
'RUSSIA#R32' => 'Russia: Cup',
'RUSSIA#R16' => 'Russia: Cup',
'RUSSIA#QF' => 'Russia: Cup',
'RUSSIA#SF' => 'Russia: Cup',
'RUSSIA#FINAL' => 'Russia: Cup',
'RUSSIA#SC' => 'Russia: Super Cup',
'825442' => 'Russia: Premier League  Championship Playoffs',
'825443' => 'Russia: Premier League  Relegation Playoffs',
'825453' => 'Russia: 1. Division Promotion Playoff',
'825454' => 'Russia: 1. Division Relegation Playoff',

'BELARUS#PR' => 'Беларусь: Вышэйшая ліга',
'BELARUS#QF' => 'Belarus: Cup',
'BELARUS#SF' => 'Belarus: Cup',
'BELARUS#R8' => 'Belarus: Cup',
'BELARUS#R16' => 'Belarus: Cup',
'BELARUS#FINAL' => 'Belarus: Cup',
'BELARUS#SC' => 'Belarus: SuperCup',
'833113' => 'Belarus: Premier League Championship Group',
'833114' => 'Belarus: Premier League Relegation Group',

'UKRAINE#PR' => 'Україна: Прем’єр-ліга',
'UKRAINE#R16' => 'Ukraine: Cup',
'UKRAINE#QF' => 'Ukraine: Cup',
'UKRAINE#SF' => 'Ukraine: Cup',
'UKRAINE#FINAL' => 'Ukraine: Cup',
'UKRAINE#SC' => 'Ukraine: SuperCup',

'BELGIUM#1A' => 'Belgium: First Division A',
'GREECE#SL' => 'Greece: Super League',
'SWITZERLAND#SL' => 'Switzerland: Super League',
'SWITZERLAND#FINAL' => 'Switzerland: FA Cup',
'TURKEY#SL' => 'Turkey: Süper Lig',
'AUSTRIA#BL' => 'Austria: Bundesliga',

'EUROPE (UEFA)#A' => 'International: UEFA Nations League',
'EUROPE (UEFA)#B' => 'International: UEFA Nations League',
'EUROPE (UEFA)#C' => 'International: UEFA Nations League',
'EUROPE (UEFA)#D' => 'International: UEFA Nations League',
'EUROPE (UEFA)#1QR' => 'International: Europa League',
'EUROPE (UEFA)#2QR' => 'International: Europa League',
'EUROPE (UEFA)#3QR' => 'International: Europa League',
'EUROPE (UEFA)#QR' => 'International: Euro qualification',
'EUROPE (UEFA)#R32' => 'International: Europa League',
'EUROPE (UEFA)#R16' => 'International: Champions League',
'EUROPE (UEFA)#PO' => 'International: Champions League',
'EUROPE (UEFA)#GS' => 'International: Champions League',
'EUROPE (UEFA)#QF' => 'International: Champions League',
'EUROPE (UEFA)#SF' => 'International: Champions League',
'EUROPE (UEFA)#FINAL' => 'International: Champions League',

'FRIENDLY GAMES#FRI' => 'International: Friendlies',
'INTERNATIONAL TOURNAMENTS#SF' => 'International: Friendlies',
'AFRICA (CAF)#2QR' => 'International: Friendlies',
'ASIA (AFC)#EAC' => 'International: Friendlies',
'WORLD (FIFA)#GS' => 'International: World Cup Group Stage',
'WORLD (FIFA)#R16' => 'International: World Cup Final Stages',
'WORLD (FIFA)#QF' => 'International: World Cup Final Stages',
'WORLD (FIFA)#SF' => 'International: World Cup Final Stages',
'WORLD (FIFA)#FINAL' => 'International: World Cup Final Stages',
'WORLD (FIFA)#WCQ' => 'International: World Cup Qualification',
'NORTH & CENTRAL AMERICA (CONCACAF)#GS' => 'International: CONCACAF Gold Cup',
'NORTH & CENTRAL AMERICA (CONCACAF)#QPO' => 'International: CONCACAF Gold Cup',
'SOUTH AMERICA (CONMEBOL)#GS' => 'International: Copa America Group Stage',
);?>