array (
  'file' => 
  array (
    'Alekhine_Bogoljubow_1929_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Висбаден',
        'event' => '14-й чемпионат Мира',
        'date' => '1929.09.06',
        'round' => '1',
        'eco' => 'D31',
        'white' => 'Алехин Александр',
        'black' => 'Боголюбов Ефим',
      ),
    ),
    'Alekhine_Bogoljubow_1929_25.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Висбаден',
        'event' => '14-й чемпионат Мира',
        'date' => '1929.11.11',
        'round' => '25',
        'eco' => 'D30',
        'white' => 'Алехин Александр',
        'black' => 'Боголюбов Ефим',
      ),
    ),
    'Alekhine_Bogoljubow_1934_26.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Германия',
        'event' => '15-й чемпионат Мира',
        'date' => '1934.06.14',
        'round' => '26',
        'eco' => 'E67',
        'white' => 'Алехин Александр',
        'black' => 'Боголюбов Ефим',
      ),
    ),
    'Alekhine_Capablanca_1927_34.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Буэнос-Айрес',
        'event' => '13-й чемпионат Мира',
        'date' => '1927.11.26',
        'round' => '34',
        'eco' => 'D51',
        'white' => 'Алехин Александр',
        'black' => 'Капабланка Хосе Рауль',
      ),
    ),
    'Alekhine_Euwe_1935_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Амстердам',
        'event' => '16-й чемпионат Мира',
        'date' => '1935.10.03',
        'round' => '1',
        'eco' => 'D17',
        'white' => 'Алехин Александр',
        'black' => 'Эйве Макс',
      ),
    ),
    'Anderssen_Kieseritzky_1851.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Лондон',
        'event' => 'Бессмертная партия',
        'date' => '1851.06.21',
        'round' => '1',
        'eco' => 'C33',
        'white' => 'Андерсен Адольф',
        'black' => 'Кизерицкий Лионель',
      ),
    ),
    'Bogoljubow_Alekhine_1934_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Германия',
        'event' => '15-й чемпионат Мира',
        'date' => '1934.04.01',
        'round' => '1',
        'eco' => 'D50',
        'white' => 'Боголюбов Ефим',
        'black' => 'Алехин Александр',
      ),
    ),
    'Botvinnik_Bronstein_1951_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '19-й чемпионат Мира',
        'date' => '1951.03.16',
        'round' => '1',
        'eco' => 'A91',
        'white' => 'Ботвинник Михаил',
        'black' => 'Бронштейн Давид',
      ),
    ),
    'Botvinnik_Euwe_1948.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '18-й чемпионат Мира',
        'date' => '1948.05.09',
        'round' => '22',
        'eco' => 'D35',
        'white' => 'Ботвинник Михаил',
        'black' => 'Эйве Макс',
      ),
    ),
    'Botvinnik_Petrosian_1963_22.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '25-й чемпионат Мира',
        'date' => '1963.05.20',
        'round' => '22',
        'eco' => 'D23',
        'white' => 'Ботвинник Михаил',
        'black' => 'Петросян Тигран',
      ),
    ),
    'Botvinnik_Smyslov_1954_24.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '20-й чемпионат Мира',
        'date' => '1954.05.13',
        'round' => '24',
        'eco' => 'E69',
        'white' => 'Ботвинник Михаил',
        'black' => 'Смыслов Василий',
      ),
    ),
    'Botvinnik_Smyslov_1957_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '21-й чемпионат Мира',
        'date' => '1957.03.05',
        'round' => '1',
        'eco' => 'A36',
        'white' => 'Ботвинник Михаил',
        'black' => 'Смыслов Василий',
      ),
    ),
    'Botvinnik_Tal_1961_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '24-й чемпионат Мира',
        'date' => '1961.03.15',
        'round' => '1',
        'eco' => 'E51',
        'white' => 'Ботвинник Михаил',
        'black' => 'Таль Михаил',
      ),
    ),
    'Botvinnik_Tal_1961_21.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '24-й чемпионат Мира',
        'date' => '1961.05.12',
        'round' => '21',
        'eco' => 'E87',
        'white' => 'Ботвинник Михаил',
        'black' => 'Таль Михаил',
      ),
    ),
    'Bronstein_Botvinnik_1951_24.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '19-й чемпионат Мира',
        'date' => '1951.05.11',
        'round' => '24',
        'eco' => 'D44',
        'white' => 'Бронштейн Давид',
        'black' => 'Ботвинник Михаил',
      ),
    ),
    'Capablanca_Alekhine_1927_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Буэнос-Айрес',
        'event' => '13-й чемпионат Мира',
        'date' => '1927.09.16',
        'round' => '1',
        'eco' => 'C01',
        'white' => 'Капабланка Хосе Рауль',
        'black' => 'Алехин Александр',
      ),
    ),
    'Capablanca_Lasker_1921_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Гавана',
        'event' => '12-й чемпионат Мира',
        'date' => '1921.03.15',
        'round' => '1',
        'eco' => 'D63',
        'white' => 'Капабланка Хосе Рауль',
        'black' => 'Ласкер Эмануил',
      ),
    ),
    'Chigorin_Steinitz_1889_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Гавана',
        'event' => '2-й чемпионат Мира',
        'date' => '1889.01.20',
        'round' => '1',
        'eco' => 'C52',
        'white' => 'Чигорин Михаил',
        'black' => 'Стейниц Вильгельм',
      ),
    ),
    'Chigorin_Steinitz_1889_17.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Гавана',
        'event' => '2-й чемпионат Мира',
        'date' => '1889.02.24',
        'round' => '17',
        'eco' => 'C52',
        'white' => 'Чигорин Михаил',
        'black' => 'Стейниц Вильгельм',
      ),
    ),
    'Chigorin_Steinitz_1892_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Гавана',
        'event' => '4-й чемпионат Мира',
        'date' => '1892.01.01',
        'round' => '1',
        'eco' => 'C52',
        'white' => 'Чигорин Михаил',
        'black' => 'Стейниц Вильгельм',
      ),
    ),
    'Chigorin_Steinitz_1892_23.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Гавана',
        'event' => '4-й чемпионат Мира',
        'date' => '1892.02.28',
        'round' => '23',
        'eco' => 'C34',
        'white' => 'Чигорин Михаил',
        'black' => 'Стейниц Вильгельм',
      ),
    ),
    'Euwe_Alekhine_1935_30.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Амстердам',
        'event' => '16-й чемпионат Мира',
        'date' => '1935.12.15',
        'round' => '30',
        'eco' => 'D78',
        'white' => 'Эйве Макс',
        'black' => 'Алехин Александр',
      ),
    ),
    'Euwe_Alekhine_1937_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Гаага',
        'event' => '17-й чемпионат Мира',
        'date' => '1937.10.05',
        'round' => '1',
        'eco' => 'D17',
        'white' => 'Эйве Макс',
        'black' => 'Алехин Александр',
      ),
    ),
    'Euwe_Alekhine_1937_25.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Гаага',
        'event' => '17-й чемпионат Мира',
        'date' => '1937.12.04',
        'round' => '25',
        'eco' => 'E46',
        'white' => 'Эйве Макс',
        'black' => 'Алехин Александр',
      ),
    ),
    'Euwe_Keres_1948_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Гаага',
        'event' => '18-й чемпионат Мира',
        'date' => '1948.03.02',
        'round' => '1',
        'eco' => 'C75',
        'white' => 'Эйве Макс',
        'black' => 'Керес Пауль',
      ),
    ),
    'Janowski_Lasker_1909_10.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Париж',
        'event' => '9-й чемпионат Мира',
        'date' => '1909.11.09',
        'round' => '10',
        'eco' => 'B34',
        'white' => 'Яновский Давид',
        'black' => 'Ласкер Эмануил',
      ),
    ),
    'Karpov_Kasparov_1984_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '31-й чемпионат Мира',
        'date' => '1984.09.10',
        'round' => '1',
        'eco' => 'B81',
        'white' => 'Карпов Анатолий',
        'black' => 'Каспаров Гарри',
      ),
    ),
    'Karpov_Kortschnoj_1978_32.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Багио',
        'event' => '29-й чемпионат Мира',
        'date' => '1978.10.17',
        'round' => '32',
        'eco' => 'A43',
        'white' => 'Карпов Анатолий',
        'black' => 'Корчной Виктор',
      ),
    ),
    'Karpov_Kortschnoj_1981_18.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Мерано',
        'event' => '30-й чемпионат Мира',
        'date' => '1981.11.18',
        'round' => '18',
        'eco' => 'C80',
        'white' => 'Карпов Анатолий',
        'black' => 'Корчной Виктор',
      ),
    ),
    'Kasparov_Anand_1995.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Нью-Йорк',
        'event' => 'Лучшая партия 1995г.',
        'date' => '1995.09.26',
        'round' => '10',
        'eco' => 'C80',
        'white' => 'Каспаров Гарри',
        'black' => 'Ананд Вишванатан',
      ),
    ),
    'Kasparov_Karpov_1985_48.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '31-й чемпионат Мира',
        'date' => '1985.02.08',
        'round' => '48',
        'eco' => 'C42',
        'white' => 'Каспаров Гарри',
        'black' => 'Карпов Анатолий',
      ),
    ),
    'Kortschnoj_Karpov_1978_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Багио',
        'event' => '29-й чемпионат Мира',
        'date' => '1978.07.18',
        'round' => '1',
        'eco' => 'D58',
        'white' => 'Корчной Виктор',
        'black' => 'Карпов Анатолий',
      ),
    ),
    'Kortschnoj_Karpov_1981_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Мерано',
        'event' => '30-й чемпионат Мира',
        'date' => '1981.10.01',
        'round' => '1',
        'eco' => 'D58',
        'white' => 'Корчной Виктор',
        'black' => 'Карпов Анатолий',
      ),
    ),
    'Lasker_Capablanca_1921_14.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Гавана',
        'event' => '12-й чемпионат Мира',
        'date' => '1921.04.20',
        'round' => '14',
        'eco' => 'C66',
        'white' => 'Ласкер Эмануил',
        'black' => 'Капабланка Хосе Рауль',
      ),
    ),
    'Lasker_Janowski_1909_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Париж',
        'event' => '9-й чемпионат Мира',
        'date' => '1909.10.19',
        'round' => '1',
        'eco' => 'C87',
        'white' => 'Ласкер Эмануил',
        'black' => 'Яновский Давид',
      ),
    ),
    'Lasker_Janowski_1910_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Берлин',
        'event' => '11-й чемпионат Мира',
        'date' => '1910.11.08',
        'round' => '1',
        'eco' => 'D32',
        'white' => 'Ласкер Эмануил',
        'black' => 'Яновский Давид',
      ),
    ),
    'Lasker_Janowski_1910_11.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Берлин',
        'event' => '11-й чемпионат Мира',
        'date' => '1910.12.08',
        'round' => '11',
        'eco' => 'C30',
        'white' => 'Ласкер Эмануил',
        'black' => 'Яновский Давид',
      ),
    ),
    'Lasker_Schlechter_1910_10.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Берлин',
        'event' => '10-й чемпионат Мира',
        'date' => '1910.02.08',
        'round' => '10',
        'eco' => 'D94',
        'white' => 'Ласкер Эмануил',
        'black' => 'Шлехтер Карл',
      ),
    ),
    'Lasker_Steinitz_1894_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Нью-Йорк',
        'event' => '5-й чемпионат Мира',
        'date' => '1894.03.15',
        'round' => '1',
        'eco' => 'C62',
        'white' => 'Ласкер Эмануил',
        'black' => 'Стейниц Вильгельм',
      ),
    ),
    'Lasker_Steinitz_1894_19.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Монреаль',
        'event' => '5-й чемпионат Мира',
        'date' => '1894.05.26',
        'round' => '19',
        'eco' => 'D40',
        'white' => 'Ласкер Эмануил',
        'black' => 'Стейниц Вильгельм',
      ),
    ),
    'Lasker_Tarrasch_1908_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Дюссельдорф',
        'event' => '8-й чемпионат Мира',
        'date' => '1908.08.17',
        'round' => '1',
        'eco' => 'C68',
        'white' => 'Ласкер Эмануил',
        'black' => 'Тарраш Зигберт',
      ),
    ),
    'Marshall_Lasker_1907_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Нью-Йорк',
        'event' => '7-й чемпионат Мира',
        'date' => '1907.01.26',
        'round' => '1',
        'eco' => 'C65',
        'white' => 'Маршалл Фрэнк',
        'black' => 'Ласкер Эмануил',
      ),
    ),
    'Marshall_Lasker_1907_15.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Нью-Йорк',
        'event' => '7-й чемпионат Мира',
        'date' => '1907.04.06',
        'round' => '15',
        'eco' => 'D53',
        'white' => 'Маршалл Фрэнк',
        'black' => 'Ласкер Эмануил',
      ),
    ),
    'Morphy_Anderssen_1858.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Париж',
        'event' => 'Матч',
        'date' => '1858.12.20',
        'round' => '7',
        'eco' => 'B01',
        'white' => 'Морфи Пол',
        'black' => 'Андерсен Адольф',
      ),
    ),
    'Morphy_Anderssen_1858_13.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Париж',
        'event' => 'Матч',
        'date' => '1858.12.20',
        'round' => '13',
        'eco' => 'C39',
        'white' => 'Морфи Пол',
        'black' => 'Андерсен Адольф',
      ),
    ),
    'Morphy_Isouard_1858.pgn' => 
    array (
      0 => 
      array (
        'site' => 'учебная',
        'event' => 'Paris',
        'date' => '1858.10.??',
        'round' => '',
        'eco' => 'C41',
        'white' => 'Морфи Пол',
        'black' => 'консультанты',
      ),
    ),
    'Petrosian_Botvinnik_1963_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '25-й чемпионат Мира',
        'date' => '1963.03.23',
        'round' => '1',
        'eco' => 'E35',
        'white' => 'Петросян Тигран',
        'black' => 'Ботвинник Михаил',
      ),
    ),
    'Petrosian_Spassky_1966_24.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '26-й чемпионат Мира',
        'date' => '1966.06.08',
        'round' => '24',
        'eco' => 'E61',
        'white' => 'Петросян Тигран',
        'black' => 'Спасский Борис',
      ),
    ),
    'Schlechter_Lasker_1910_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Вена',
        'event' => '10-й чемпионат Мира',
        'date' => '1910.01.07',
        'round' => '1',
        'eco' => 'C66',
        'white' => 'Шлехтер Карл',
        'black' => 'Ласкер Эмануил',
      ),
    ),
    'Smyslov_Botvinnik_1954_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '20-й чемпионат Мира',
        'date' => '1954.03.16',
        'round' => '1',
        'eco' => 'C18',
        'white' => 'Смыслов Василий',
        'black' => 'Ботвинник Михаил',
      ),
    ),
    'Smyslov_Botvinnik_1957_22.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '21-й чемпионат Мира',
        'date' => '1957.04.27',
        'round' => '22',
        'eco' => 'C13',
        'white' => 'Смыслов Василий',
        'black' => 'Ботвинник Михаил',
      ),
    ),
    'Smyslov_Botvinnik_1958_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '22-й чемпионат Мира',
        'date' => '1958.03.04',
        'round' => '1',
        'eco' => 'B11',
        'white' => 'Смыслов Василий',
        'black' => 'Ботвинник Михаил',
      ),
    ),
    'Smyslov_Botvinnik_1958_23.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '22-й чемпионат Мира',
        'date' => '1958.05.08',
        'round' => '23',
        'eco' => 'A05',
        'white' => 'Смыслов Василий',
        'black' => 'Ботвинник Михаил',
      ),
    ),
    'Smyslov_Reshevsky_1948.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '18-й чемпионат Мира',
        'date' => '1948.03.02',
        'round' => '1',
        'eco' => 'C99',
        'white' => 'Смыслов Василий',
        'black' => 'Решевский Самуэль',
      ),
    ),
    'Spassky_Fischer_1972_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Рейкьявик',
        'event' => '28-й чемпионат Мира',
        'date' => '1972.07.11',
        'round' => '1',
        'eco' => 'E56',
        'white' => 'Спасский Борис',
        'black' => 'Фишер Роберт',
      ),
    ),
    'Spassky_Fischer_1972_21.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Рейкьявик',
        'event' => '28-й чемпионат Мира',
        'date' => '1972.08.31',
        'round' => '21',
        'eco' => 'B46',
        'white' => 'Спасский Борис',
        'black' => 'Фишер Роберт',
      ),
    ),
    'Spassky_Petrosian_1966_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '26-й чемпионат Мира',
        'date' => '1966.04.11',
        'round' => '1',
        'eco' => 'B19',
        'white' => 'Спасский Борис',
        'black' => 'Петросян Тигран',
      ),
    ),
    'Spassky_Petrosian_1969_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '27-й чемпионат Мира',
        'date' => '1969.04.14',
        'round' => '1',
        'eco' => 'B42',
        'white' => 'Спасский Борис',
        'black' => 'Петросян Тигран',
      ),
    ),
    'Spassky_Petrosian_1969_23.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '27-й чемпионат Мира',
        'date' => '1969.06.16',
        'round' => '23',
        'eco' => 'B48',
        'white' => 'Спасский Борис',
        'black' => 'Петросян Тигран',
      ),
    ),
    'Steinitz_Gunsberg_1890_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Нью-Йорк',
        'event' => '3-й чемпионат Мира',
        'date' => '1890.12.09',
        'round' => '1',
        'eco' => 'D35',
        'white' => 'Стейниц Вильгельм',
        'black' => 'Гунсберг Исидор',
      ),
    ),
    'Steinitz_Gunsberg_1891_19.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Нью-Йорк',
        'event' => '3-й чемпионат Мира',
        'date' => '1891.01.22',
        'round' => '19',
        'eco' => 'D40',
        'white' => 'Стейниц Вильгельм',
        'black' => 'Гунсберг Исидор',
      ),
    ),
    'Steinitz_Lasker_1896_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '6-й чемпионат Мира',
        'date' => '1896.11.07',
        'round' => '1',
        'eco' => 'C54',
        'white' => 'Стейниц Вильгельм',
        'black' => 'Ласкер Эмануил',
      ),
    ),
    'Steinitz_Lasker_1897_17.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '6-й чемпионат Мира',
        'date' => '1897.01.11',
        'round' => '17',
        'eco' => 'D60',
        'white' => 'Стейниц Вильгельм',
        'black' => 'Ласкер Эмануил',
      ),
    ),
    'Steinitz_Zukertort_1886_20.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Новый Орлеан',
        'event' => '1-й чемпионат Мира',
        'date' => '1886.03.29',
        'round' => '20',
        'eco' => 'C25',
        'white' => 'Стейниц Вильгельм',
        'black' => 'Цукерторт Иоганн',
      ),
    ),
    'Tal_Botvinnik_1960_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '23-й чемпионат Мира',
        'date' => '1960.03.15',
        'round' => '1',
        'eco' => 'C18',
        'white' => 'Таль Михаил',
        'black' => 'Ботвинник Михаил',
      ),
    ),
    'Tal_Botvinnik_1960_21.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Москва',
        'event' => '23-й чемпионат Мира',
        'date' => '1960.05.07',
        'round' => '21',
        'eco' => 'E19',
        'white' => 'Таль Михаил',
        'black' => 'Ботвинник Михаил',
      ),
    ),
    'Tarrasch_Lasker_1908_16.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Мюнхен',
        'event' => '8-й чемпионат Мира',
        'date' => '1908.09.30',
        'round' => '16',
        'eco' => 'C49',
        'white' => 'Тарраш Зигберт',
        'black' => 'Ласкер Эмануил',
      ),
    ),
    'Zukertort_Steinitz_1886_1.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Нью-Йорк',
        'event' => '1-й чемпионат Мира',
        'date' => '1886.01.11',
        'round' => '1',
        'eco' => 'D11',
        'white' => 'Цукерторт Иоганн',
        'black' => 'Стейниц Вильгельм',
      ),
    ),
    'ardashev_ligay_2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2020',
        'date' => '2020.02.01',
        'round' => '7',
        'eco' => 'B10',
        'white' => 'Ардашев Артем',
        'black' => 'Лигай Руслан',
      ),
    ),
    'ardashev_ligay_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.12.01',
        'round' => '8',
        'eco' => 'C01',
        'white' => 'Ардашев Артем',
        'black' => 'Лигай Руслан',
      ),
    ),
    'ardashev_shelkovskiy_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.23',
        'round' => '5',
        'eco' => 'D10',
        'white' => 'Ардашев Артем',
        'black' => 'Шелковский Артем',
      ),
    ),
    'ardashev_tishenkovik_2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2020',
        'date' => '2020.02.08',
        'round' => '9',
        'eco' => 'B40',
        'white' => 'Ардашев Артем',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'ardashev_ustinov_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.10',
        'round' => '2',
        'eco' => 'B13',
        'white' => 'Ардашев Артем',
        'black' => 'Устинов Александр',
      ),
    ),
    'dedikov_djachenkokyr_122018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.16',
        'round' => '6',
        'eco' => 'B01',
        'white' => 'Дедиков Геннадий',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'dedikov_dudnik_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.12',
        'round' => '3',
        'eco' => 'B20',
        'white' => 'Дедиков Геннадий',
        'black' => 'Дудник Татьяна',
      ),
    ),
    'dedikov_grizenko_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.09',
        'round' => '11',
        'eco' => 'D80',
        'white' => 'Дедиков Геннадий',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'dedikov_shelkovskiy_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.23',
        'round' => '8',
        'eco' => 'B12',
        'white' => 'Дедиков Геннадий',
        'black' => 'Шелковский Артем',
      ),
    ),
    'dedikov_tishenkovik_122018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.09',
        'round' => '4',
        'eco' => 'B20',
        'white' => 'Дедиков Геннадий',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'dedikov_volginalex_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.02',
        'round' => '2',
        'eco' => 'C01',
        'white' => 'Дедиков Геннадий',
        'black' => 'Волгин Александр',
      ),
    ),
    'dedikov_zabobonin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.26',
        'round' => '7',
        'eco' => 'B01',
        'white' => 'Дедиков Геннадий',
        'black' => 'Забобонин Сергей',
      ),
    ),
    'demjanchenko_dudnik_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.08',
        'round' => '3',
        'eco' => 'B76',
        'white' => 'Демьянченко Валерий',
        'black' => 'Дудник Татьяна',
      ),
    ),
    'djachenkokyr_dedikov_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.06',
        'round' => '2',
        'eco' => 'B22',
        'white' => 'Дьяченко Кирилл',
        'black' => 'Дедиков Геннадий',
      ),
    ),
    'djachenkokyr_dudnik_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.13',
        'round' => '4',
        'eco' => 'B76',
        'white' => 'Дьяченко Кирилл',
        'black' => 'Дудник Татьяна',
      ),
    ),
    'djachenkokyr_dudnik_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.27',
        'round' => '9',
        'eco' => 'B76',
        'white' => 'Дьяченко Кирилл',
        'black' => 'Дудник Татьяна',
      ),
    ),
    'djachenkokyr_grechkin_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.15',
        'round' => '5',
        'eco' => 'C42',
        'white' => 'Дьяченко Кирилл',
        'black' => 'Гречкин Евгений',
      ),
    ),
    'djachenkokyr_grizenko_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.27',
        'round' => '7',
        'eco' => 'B40',
        'white' => 'Дьяченко Кирилл',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'djachenkokyr_gulinskiy_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.03',
        'round' => '9',
        'eco' => 'B50',
        'white' => 'Дьяченко Кирилл',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'djachenkokyr_leonov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.06',
        'round' => '1',
        'eco' => 'C01',
        'white' => 'Дьяченко Кирилл',
        'black' => 'Леонов Владимир',
      ),
    ),
    'djachenkokyr_samsonov_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.20',
        'round' => '6',
        'eco' => 'B90',
        'white' => 'Дьяченко Кирилл',
        'black' => 'Самсонов Евгений',
      ),
    ),
    'djachenkokyr_samsonov_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.22',
        'round' => '7',
        'eco' => 'B90',
        'white' => 'Дьяченко Кирилл',
        'black' => 'Самсонов Евгений',
      ),
    ),
    'djachenkokyr_sudnizyn_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.03',
        'round' => '10',
        'eco' => 'C50',
        'white' => 'Дьяченко Кирилл',
        'black' => 'Судницын Николай',
      ),
    ),
    'djachenkokyr_zabobonin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.10',
        'round' => '12',
        'eco' => 'D13',
        'white' => 'Дьяченко Кирилл',
        'black' => 'Забобонин Сергей',
      ),
    ),
    'djachenkoserg-zobnin_06012018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.06',
        'round' => '1',
        'eco' => 'D45',
        'white' => 'Дьяченко Сергей',
        'black' => 'Зобнин Валентин',
      ),
    ),
    'djachenkoserg_djachenkokyr_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.04',
        'round' => '10',
        'eco' => 'D12',
        'white' => 'Дьяченко Сергей',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'djachenkoserg_rudv_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.27',
        'round' => '7',
        'eco' => 'A41',
        'white' => 'Дьяченко Сергей',
        'black' => 'Рудь Виктор',
      ),
    ),
    'djachenkoserg_sudnizyn_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.18',
        'round' => '14',
        'eco' => 'D94',
        'white' => 'Дьяченко Сергей',
        'black' => 'Судницын Николай',
      ),
    ),
    'djachenkoserg_telmanov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.11',
        'round' => '12',
        'eco' => 'A30',
        'white' => 'Дьяченко Сергей',
        'black' => 'Тельманов Андрей',
      ),
    ),
    'djachenkoserg_volginalex_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.20',
        'round' => '5',
        'eco' => 'E20',
        'white' => 'Дьяченко Сергей',
        'black' => 'Волгин Александр',
      ),
    ),
    'djachenkoserg_zabobonin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.13',
        'round' => '3',
        'eco' => 'D15',
        'white' => 'Дьяченко Сергей',
        'black' => 'Забобонин Сергей',
      ),
    ),
    'dudnik_grechkin_122018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.22',
        'round' => '7',
        'eco' => 'A58',
        'white' => 'Дудник Татьяна',
        'black' => 'Гречкин Евгений',
      ),
    ),
    'dudnik_grechkin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.16',
        'round' => '13',
        'eco' => 'D46',
        'white' => 'Дудник Татьяна',
        'black' => 'Гречкин Евгений',
      ),
    ),
    'dudnik_gulinskiy_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.09',
        'round' => '11',
        'eco' => 'D45',
        'white' => 'Дудник Татьяна',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'dudnik_samsonov_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.19',
        'round' => '5',
        'eco' => 'E12',
        'white' => 'Дудник Татьяна',
        'black' => 'Самсонов Евгений',
      ),
    ),
    'dudnik_shelkovskiy_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.09',
        'round' => '4',
        'eco' => 'D11',
        'white' => 'Дудник Татьяна',
        'black' => 'Шелковский Артем',
      ),
    ),
    'dudnik_sudnizyn_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.26',
        'round' => '7',
        'eco' => 'D11',
        'white' => 'Дудник Татьяна',
        'black' => 'Судницын Николай',
      ),
    ),
    'dudnik_tishenkovik_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.02',
        'round' => '9',
        'eco' => 'D45',
        'white' => 'Дудник Татьяна',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'dudnik_tishenkovik_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.16',
        'round' => '6',
        'eco' => 'D37',
        'white' => 'Дудник Татьяна',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'dudnik_zelyak_122018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.01',
        'round' => '1',
        'eco' => 'A49',
        'white' => 'Дудник Татьяна',
        'black' => 'Зеляк Александр',
      ),
    ),
    'grechkin_dedikov_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.10',
        'round' => '12',
        'eco' => 'D15',
        'white' => 'Гречкин Евгений',
        'black' => 'Дедиков Геннадий',
      ),
    ),
    'grechkin_gulinskiy_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.26',
        'round' => '7',
        'eco' => 'E01',
        'white' => 'Гречкин Евгений',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'grechkin_jachenkokyr_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.02',
        'round' => '9',
        'eco' => 'A95',
        'white' => 'Гречкин Евгений',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'grechkin_samsonov_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.05',
        'round' => '1',
        'eco' => 'E21',
        'white' => 'Гречкин Евгений',
        'black' => 'Самсонов Евгений',
      ),
    ),
    'grechkin_samsonov_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.09',
        'round' => '4',
        'eco' => 'A45',
        'white' => 'Гречкин Евгений',
        'black' => 'Самсонов Евгений',
      ),
    ),
    'grechkin_skorikov_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.08',
        'round' => '3',
        'eco' => 'D30',
        'white' => 'Гречкин Евгений',
        'black' => 'Скориков Александр',
      ),
    ),
    'grechkin_tishenkovik_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.19',
        'round' => '5',
        'eco' => 'D46',
        'white' => 'Гречкин Евгений',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'grechkin_tishenkovik_2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2020',
        'date' => '2020.01.12',
        'round' => '2',
        'eco' => 'D03',
        'white' => 'Гречкин Евгений',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'grechkin_tishnkovik_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.23',
        'round' => '8',
        'eco' => 'D46',
        'white' => 'Гречкин Евгений',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'grechkin_zobnin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.03',
        'round' => '10',
        'eco' => 'D02',
        'white' => 'Гречкин Евгений',
        'black' => 'Зобнин Валентин',
      ),
    ),
    'grizenko_djachenkokyr_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.26',
        'round' => '7',
        'eco' => 'A36',
        'white' => 'Гриценко Сергей',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'grizenko_djachenkoserg_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.14',
        'round' => '4',
        'eco' => 'A32',
        'white' => 'Гриценко Сергей',
        'black' => 'Дьяченко Сергей',
      ),
    ),
    'grizenko_dudnik_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.11',
        'round' => '12',
        'eco' => 'D92',
        'white' => 'Гриценко Сергей',
        'black' => 'Дудник Татьяна',
      ),
    ),
    'grizenko_grechkin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.27',
        'round' => '8',
        'eco' => 'D58',
        'white' => 'Гриценко Сергей',
        'black' => 'Гречкин Евгений',
      ),
    ),
    'grizenko_irupin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.28',
        'round' => '8',
        'eco' => 'C50',
        'white' => 'Гриценко Сергей',
        'black' => 'Ирюпин Андрей',
      ),
    ),
    'grizenko_konoplev_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.11',
        'round' => '12',
        'eco' => 'D55',
        'white' => 'Гриценко Сергей',
        'black' => 'Коноплев Александр',
      ),
    ),
    'grizenko_leonov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.04',
        'round' => '10',
        'eco' => 'D63',
        'white' => 'Гриценко Сергей',
        'black' => 'Леонов Владимир',
      ),
    ),
    'grizenko_leonov_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.03',
        'round' => '10',
        'eco' => 'D63',
        'white' => 'Гриценко Сергей',
        'black' => 'Леонов Владимир',
      ),
    ),
    'grizenko_makarov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.21',
        'round' => '6',
        'eco' => 'A85',
        'white' => 'Гриценко Сергей',
        'black' => 'Макаров Валентин',
      ),
    ),
    'grizenko_rudv_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.06',
        'round' => '1',
        'eco' => 'B01',
        'white' => 'Гриценко Сергей',
        'black' => 'Рудь Виктор',
      ),
    ),
    'grizenko_uglev_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.18',
        'round' => '14',
        'eco' => 'C92',
        'white' => 'Гриценко Сергей',
        'black' => 'Углев Эдуард',
      ),
    ),
    'grizenko_volginalex_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.07',
        'round' => '2',
        'eco' => 'C02',
        'white' => 'Гриценко Сергей',
        'black' => 'Волгин Александр',
      ),
    ),
    'grizenko_zabobonin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.12',
        'round' => '3',
        'eco' => 'B11',
        'white' => 'Гриценко Сергей',
        'black' => 'Забобонин Сергей',
      ),
    ),
    'gulinskiy-uglev_06012018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.06',
        'round' => '1',
        'eco' => 'C74',
        'white' => 'Гулинский Владимир',
        'black' => 'Углев Эдуард',
      ),
    ),
    'gulinskiy_dedikov_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.03',
        'round' => '10',
        'eco' => 'C96',
        'white' => 'Гулинский Владимир',
        'black' => 'Дедиков Геннадий',
      ),
    ),
    'gulinskiy_djachenkokyr_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.19',
        'round' => '5',
        'eco' => 'C10',
        'white' => 'Гулинский Владимир',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'gulinskiy_djachenkoserg_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.21',
        'round' => '6',
        'eco' => 'B76',
        'white' => 'Гулинский Владимир',
        'black' => 'Дьяченко Сергей',
      ),
    ),
    'gulinskiy_grizenko_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.18',
        'round' => '3',
        'eco' => 'B42',
        'white' => 'Гулинский Владимир',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'gulinskiy_grizenko_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.20',
        'round' => '6',
        'eco' => 'B80',
        'white' => 'Гулинский Владимир',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'gulinskiy_irupin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.04',
        'round' => '10',
        'eco' => 'C41',
        'white' => 'Гулинский Владимир',
        'black' => 'Ирюпин Андрей',
      ),
    ),
    'gulinskiy_konoplev_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.18',
        'round' => '14',
        'eco' => 'C65',
        'white' => 'Гулинский Владимир',
        'black' => 'Коноплев Александр',
      ),
    ),
    'gulinskiy_leonov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.11',
        'round' => '12',
        'eco' => 'C12',
        'white' => 'Гулинский Владимир',
        'black' => 'Леонов Владимир',
      ),
    ),
    'gulinskiy_makarov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.28',
        'round' => '8',
        'eco' => 'B01',
        'white' => 'Гулинский Владимир',
        'black' => 'Макаров Валентин',
      ),
    ),
    'gulinskiy_rudv_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.20',
        'round' => '5',
        'eco' => 'B01',
        'white' => 'Гулинский Владимир',
        'black' => 'Рудь Виктор',
      ),
    ),
    'gulinskiy_sudnizyn_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.05',
        'round' => '1',
        'eco' => 'B15',
        'white' => 'Гулинский Владимир',
        'black' => 'Судницын Николай',
      ),
    ),
    'gulinskiy_tishenkovik_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.12',
        'round' => '3',
        'eco' => 'B07',
        'white' => 'Гулинский Владимир',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'gulinskiy_zobnin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.27',
        'round' => '8',
        'eco' => 'C77',
        'white' => 'Гулинский Владимир',
        'black' => 'Зобнин Валентин',
      ),
    ),
    'irupin_dedikov_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.29',
        'round' => '9',
        'eco' => 'B30',
        'white' => 'Ирюпин Андрей',
        'black' => 'Дедиков Геннадий',
      ),
    ),
    'irupin_djachenkokyr_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.23',
        'round' => '8',
        'eco' => 'B02',
        'white' => 'Ирюпин Андрей',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'irupin_djachenkoserg_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.10',
        'round' => '11',
        'eco' => 'B50',
        'white' => 'Ирюпин Андрей',
        'black' => 'Дьяченко Сергей',
      ),
    ),
    'irupin_makarov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.17',
        'round' => '13',
        'eco' => 'B02',
        'white' => 'Ирюпин Андрей',
        'black' => 'Макаров Валентин',
      ),
    ),
    'irupin_oganesyananna_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.02',
        'round' => '2',
        'eco' => 'C50',
        'white' => 'Ирюпин Андрей',
        'black' => 'Оганесян Анна',
      ),
    ),
    'irupin_oganesyanarsh_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.16',
        'round' => '6',
        'eco' => 'C53',
        'white' => 'Ирюпин Андрей',
        'black' => 'Оганесян Аршак',
      ),
    ),
    'irupin_rudv_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.24',
        'round' => '15',
        'eco' => 'B50',
        'white' => 'Ирюпин Андрей',
        'black' => 'Рудь Виктор',
      ),
    ),
    'irupin_sudnizyn_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.13',
        'round' => '3',
        'eco' => 'B12',
        'white' => 'Ирюпин Андрей',
        'black' => 'Судницын Николай',
      ),
    ),
    'irupin_telmanov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.06',
        'round' => '1',
        'eco' => 'B30',
        'white' => 'Ирюпин Андрей',
        'black' => 'Тельманов Андрей',
      ),
    ),
    'irupin_volginalex_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.03',
        'round' => '9',
        'eco' => 'C00',
        'white' => 'Ирюпин Андрей',
        'black' => 'Волгин Александр',
      ),
    ),
    'irupin_volginalex_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.09',
        'round' => '4',
        'eco' => 'C00',
        'white' => 'Ирюпин Андрей',
        'black' => 'Волгин Александр',
      ),
    ),
    'irupin_zabobonin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.27',
        'round' => '7',
        'eco' => 'B10',
        'white' => 'Ирюпин Андрей',
        'black' => 'Забобонин Сергей',
      ),
    ),
    'irupin_zobnin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.20',
        'round' => '5',
        'eco' => 'C50',
        'white' => 'Ирюпин Андрей',
        'black' => 'Зобнин Валентин',
      ),
    ),
    'konoplev_abramov_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.10',
        'round' => '2',
        'eco' => 'B02',
        'white' => 'Коноплев Александр',
        'black' => 'Абрамов Кирилл',
      ),
    ),
    'konoplev_ardashev_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.16',
        'round' => '3',
        'eco' => 'C87',
        'white' => 'Коноплев Александр',
        'black' => 'Ардашев Артем',
      ),
    ),
    'konoplev_djachenkoserg_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.24',
        'round' => '15',
        'eco' => 'B31',
        'white' => 'Коноплев Александр',
        'black' => 'Дьяченко Сергей',
      ),
    ),
    'konoplev_irupin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.14',
        'round' => '4',
        'eco' => 'C66',
        'white' => 'Коноплев Александр',
        'black' => 'Ирюпин Андрей',
      ),
    ),
    'konoplev_makarov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.07',
        'round' => '2',
        'eco' => 'B01',
        'white' => 'Коноплев Александр',
        'black' => 'Макаров Валентин',
      ),
    ),
    'konoplev_nikolaev_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.12.07',
        'round' => '9',
        'eco' => 'C01',
        'white' => 'Коноплев Александр',
        'black' => 'Николаев Никита',
      ),
    ),
    'konoplev_palladin_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.23',
        'round' => '5',
        'eco' => 'B32',
        'white' => 'Коноплев Александр',
        'black' => 'Палладин Дмитрий',
      ),
    ),
    'konoplev_volginalex_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.17',
        'round' => '13',
        'eco' => 'C01',
        'white' => 'Коноплев Александр',
        'black' => 'Волгин Александр',
      ),
    ),
    'kotlyarov_irupin_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.08',
        'round' => '3',
        'eco' => 'C47',
        'white' => 'Котляров Егор',
        'black' => 'Ирюпин Андрей',
      ),
    ),
    'kotlyarov_samsonov_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.01',
        'round' => '1',
        'eco' => 'B23',
        'white' => 'Котляров Егор',
        'black' => 'Самсонов Евгений',
      ),
    ),
    'kotlyarov_zelyak_122018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.22',
        'round' => '7',
        'eco' => 'B08',
        'white' => 'Котляров Егор',
        'black' => 'Зеляк Александр',
      ),
    ),
    'leonov_dedikov_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.08',
        'round' => '1',
        'eco' => 'D06',
        'white' => 'Леонов Владимир',
        'black' => 'Дедиков Геннадий',
      ),
    ),
    'leonov_djachenkokyr_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.15',
        'round' => '13',
        'eco' => 'E90',
        'white' => 'Леонов Владимир',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'leonov_djachenkserg_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.17',
        'round' => '13',
        'eco' => 'D37',
        'white' => 'Леонов Владимир',
        'black' => 'Дьяченко Сергей',
      ),
    ),
    'leonov_grechkin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.07',
        'round' => '11',
        'eco' => 'D91',
        'white' => 'Леонов Владимир',
        'black' => 'Гречкин Евгений',
      ),
    ),
    'leonov_gulinskiy_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.10',
        'round' => '9',
        'eco' => 'D66',
        'white' => 'Леонов Владимир',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'leonov_irupin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.07',
        'round' => '2',
        'eco' => 'D53',
        'white' => 'Леонов Владимир',
        'black' => 'Ирюпин Андрей',
      ),
    ),
    'leonov_sudnizyn_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.20',
        'round' => '5',
        'eco' => 'D44',
        'white' => 'Леонов Владимир',
        'black' => 'Судницын Николай',
      ),
    ),
    'leonov_sudnizyn_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.02',
        'round' => '5',
        'eco' => 'D02',
        'white' => 'Леонов Владимир',
        'black' => 'Судницын Николай',
      ),
    ),
    'leonov_tishnkovik_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.26',
        'round' => '7',
        'eco' => 'D31',
        'white' => 'Леонов Владимир',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'leonov_volginalex_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.10',
        'round' => '11',
        'eco' => 'D53',
        'white' => 'Леонов Владимир',
        'black' => 'Волгин Александр',
      ),
    ),
    'ligay_konoplev_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.30',
        'round' => '7',
        'eco' => 'C45',
        'white' => 'Лигай Руслан',
        'black' => 'Коноплев Александр',
      ),
    ),
    'ligay_skorikov_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.23',
        'round' => '5',
        'eco' => 'C45',
        'white' => 'Лигай Руслан',
        'black' => 'Скориков Александр',
      ),
    ),
    'ligay_ustinov_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.12.07',
        'round' => '9',
        'eco' => 'B10',
        'white' => 'Лигай Руслан',
        'black' => 'Устинов Александр',
      ),
    ),
    'loktionov_shlkovskiy_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.09',
        'round' => '1',
        'eco' => 'B13',
        'white' => 'Локтионов Максим',
        'black' => 'Шелковский Артем',
      ),
    ),
    'makarov_djachenkokyr_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.11',
        'round' => '12',
        'eco' => 'C46',
        'white' => 'Макаров Валентин',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'makarov_djachenkoserg_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.03',
        'round' => '9',
        'eco' => 'B34',
        'white' => 'Макаров Валентин',
        'black' => 'Дьяченко Сергей',
      ),
    ),
    'makarov_rudv_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.10',
        'round' => '11',
        'eco' => 'B01',
        'white' => 'Макаров Валентин',
        'black' => 'Рудь Виктор',
      ),
    ),
    'makarov_telmanov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.18',
        'round' => '14',
        'eco' => 'B23',
        'white' => 'Макаров Валентин',
        'black' => 'Тельманов Андрей',
      ),
    ),
    'makarov_volginalex_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.27',
        'round' => '7',
        'eco' => 'C06',
        'white' => 'Макаров Валентин',
        'black' => 'Волгин Александр',
      ),
    ),
    'makarovv_sudnizynn_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.06',
        'round' => '1',
        'eco' => 'B10',
        'white' => 'Макаров Валентин',
        'black' => 'Судницын Николай',
      ),
    ),
    'moskalenko_grechkin_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.02',
        'round' => '2',
        'eco' => 'B07',
        'white' => 'Москаленко Игорь',
        'black' => 'Гречкин Евгений',
      ),
    ),
    'nikolaev_tishenkovld_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.17',
        'round' => '4',
        'eco' => 'B13',
        'white' => 'Николаев Никита',
        'black' => 'Тищенко Владимир',
      ),
    ),
    'oganesyanan_moskalenko_122018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.08',
        'round' => '3',
        'eco' => 'C57',
        'white' => 'Оганесян Анна',
        'black' => 'Москаленко Игорь',
      ),
    ),
    'oganesyananna_shelkovskiy_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.12.07',
        'round' => '9',
        'eco' => 'B12',
        'white' => 'Оганесян Анна',
        'black' => 'Шелковский Артем',
      ),
    ),
    'oganesyananna_skorikov_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.01',
        'round' => '1',
        'eco' => 'C55',
        'white' => 'Оганесян Анна',
        'black' => 'Скориков Александр',
      ),
    ),
    'oganesyananna_ustinov_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.17',
        'round' => '4',
        'eco' => 'B13',
        'white' => 'Оганесян Анна',
        'black' => 'Устинов Александр',
      ),
    ),
    'oganesyanarsh_arashev_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.09',
        'round' => '1',
        'eco' => 'C50',
        'white' => 'Оганесян Аршак',
        'black' => 'Ардашев Артем',
      ),
    ),
    'oganesyanarsh_dedikov_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.08',
        'round' => '3',
        'eco' => 'C50',
        'white' => 'Оганесян Аршак',
        'black' => 'Дедиков Геннадий',
      ),
    ),
    'palladin_ligay_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.24',
        'round' => '6',
        'eco' => 'C01',
        'white' => 'Палладин Дмитрий',
        'black' => 'Лигай Руслан',
      ),
    ),
    'palladin_zelyak_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.12.07',
        'round' => '9',
        'eco' => 'C01',
        'white' => 'Палладин Дмитрий',
        'black' => 'Зеляк Александр',
      ),
    ),
    'rudv_djachenkokyr_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.12',
        'round' => '3',
        'eco' => 'E71',
        'white' => 'Рудь Виктор',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'rudv_gulinskiy_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.13',
        'round' => '4',
        'eco' => 'D13',
        'white' => 'Рудь Виктор',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'rudv_sudnizyn_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.21',
        'round' => '6',
        'eco' => 'C10',
        'white' => 'Рудь Виктор',
        'black' => 'Судницын Николай',
      ),
    ),
    'rudv_telmanov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.07',
        'round' => '2',
        'eco' => 'A44',
        'white' => 'Рудь Виктор',
        'black' => 'Тельманов Андрей',
      ),
    ),
    'rudv_uglev_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.11',
        'round' => '12',
        'eco' => 'D02',
        'white' => 'Рудь Виктор',
        'black' => 'Углев Эдуард',
      ),
    ),
    'rudv_zabobonin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.18',
        'round' => '14',
        'eco' => 'D00',
        'white' => 'Рудь Виктор',
        'black' => 'Забобонин Сергей',
      ),
    ),
    'rudv_zabobonin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.05',
        'round' => '1',
        'eco' => 'B01',
        'white' => 'Рудь Виктор',
        'black' => 'Забобонин Сергей',
      ),
    ),
    'rudv_zobnin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.04',
        'round' => '10',
        'eco' => 'D10',
        'white' => 'Рудь Виктор',
        'black' => 'Зобнин Валентин',
      ),
    ),
    'samsonov_dedikov_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.13',
        'round' => '4',
        'eco' => 'A60',
        'white' => 'Самсонов Евгений',
        'black' => 'Дедиков Геннадий',
      ),
    ),
    'samsonov_demjanchenko_122018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.02',
        'round' => '2',
        'eco' => 'D45',
        'white' => 'Самсонов Евгений',
        'black' => 'Демьянченко Валерий',
      ),
    ),
    'samsonov_oganesyananna_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.29',
        'round' => '9',
        'eco' => 'E71',
        'white' => 'Самсонов Евгений',
        'black' => 'Оганесян Анна',
      ),
    ),
    'samsonov_shelkovskiy_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.16',
        'round' => '6',
        'eco' => 'D31',
        'white' => 'Самсонов Евгений',
        'black' => 'Шелковский Артем',
      ),
    ),
    'samsonov_zelyak_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.23',
        'round' => '8',
        'eco' => 'E80',
        'white' => 'Самсонов Евгений',
        'black' => 'Зеляк Александр',
      ),
    ),
    'samsonov_zobnin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.06',
        'round' => '2',
        'eco' => 'D15',
        'white' => 'Самсонов Евгений',
        'black' => 'Зобнин Валентин',
      ),
    ),
    'shelkovski_grechkin_122018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.29',
        'round' => '9',
        'eco' => 'D10',
        'white' => 'Шелковский Артем',
        'black' => 'Гречкин Евгений',
      ),
    ),
    'shelkovskij_irupin_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.15',
        'round' => '5',
        'eco' => 'E51',
        'white' => 'Шелковский Артем',
        'black' => 'Ирюпин Андрей',
      ),
    ),
    'shelkovskiy_ligay_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.17',
        'round' => '4',
        'eco' => 'D02',
        'white' => 'Шелковский Артем',
        'black' => 'Лигай Руслан',
      ),
    ),
    'shelkovskiy_moskalenko_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.22',
        'round' => '7',
        'eco' => 'E10',
        'white' => 'Шелковский Артем',
        'black' => 'Москаленко Игорь',
      ),
    ),
    'shelkovskiy_tishnkovld_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.08',
        'round' => '3',
        'eco' => 'D07',
        'white' => 'Шелковский Артем',
        'black' => 'Тищенко Владимир',
      ),
    ),
    'shirinnyan_konoplev_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.06',
        'round' => '1',
        'eco' => 'D02',
        'white' => 'Ширинян Вазир',
        'black' => 'Коноплев Александр',
      ),
    ),
    'shirinyan_gulinskiy_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.27',
        'round' => '7',
        'eco' => 'D02',
        'white' => 'Ширинян Вазир',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'shirinyan_uglev_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.13',
        'round' => '3',
        'eco' => 'D02',
        'white' => 'Ширинян Вазир',
        'black' => 'Углев Эдуард',
      ),
    ),
    'skorikov_ardashev_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.12.07',
        'round' => '9',
        'eco' => 'C50',
        'white' => 'Скориков Александр',
        'black' => 'Ардашев Артем',
      ),
    ),
    'skorikov_konoplev_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.17',
        'round' => '4',
        'eco' => 'C47',
        'white' => 'Скориков Александр',
        'black' => 'Коноплев Александр',
      ),
    ),
    'skorikov_nikolaev_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.16',
        'round' => '3',
        'eco' => 'C01',
        'white' => 'Скориков Александр',
        'black' => 'Николаев Никита',
      ),
    ),
    'skorikov_samsonov_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.15',
        'round' => '5',
        'eco' => 'B20',
        'white' => 'Скориков Александр',
        'black' => 'Самсонов Евгений',
      ),
    ),
    'skorikov_tishenkovik_pf2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.02',
        'round' => '2',
        'eco' => 'C42',
        'white' => 'Скориков Александр',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'skorikov_tishenkovld_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.29',
        'round' => '9',
        'eco' => 'B23',
        'white' => 'Скориков Александр',
        'black' => 'Тищенко Владимир',
      ),
    ),
    'skorikov_ustinov_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.24',
        'round' => '6',
        'eco' => 'B50',
        'white' => 'Скориков Александр',
        'black' => 'Устинов Александр',
      ),
    ),
    'sudnizyn_dedikov_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.20',
        'round' => '6',
        'eco' => 'B23',
        'white' => 'Судницын Николай',
        'black' => 'Дедиков Геннадий',
      ),
    ),
    'sudnizyn_djachenkokyr_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.07',
        'round' => '2',
        'eco' => 'C24',
        'white' => 'Судницын Николай',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'sudnizyn_grizenko_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.10',
        'round' => '11',
        'eco' => 'D42',
        'white' => 'Судницын Николай',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'sudnizyn_grizenko_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.06',
        'round' => '2',
        'eco' => 'B23',
        'white' => 'Судницын Николай',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'sudnizyn_gulinskiy_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.17',
        'round' => '13',
        'eco' => 'B50',
        'white' => 'Судницын Николай',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'sudnizyn_telmanov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.14',
        'round' => '4',
        'eco' => 'B23',
        'white' => 'Судницын Николай',
        'black' => 'Тельманов Андрей',
      ),
    ),
    'sudnizyn_uglev_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.03',
        'round' => '9',
        'eco' => 'C55',
        'white' => 'Судницын Николай',
        'black' => 'Углев Эдуард',
      ),
    ),
    'sudnizyn_zabobonin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.09',
        'round' => '11',
        'eco' => 'B12',
        'white' => 'Судницын Николай',
        'black' => 'Забобонин Сергей',
      ),
    ),
    'telmanov_djachnkokyr_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.24',
        'round' => '15',
        'eco' => 'B10',
        'white' => 'Тельманов Андрей',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'telmanov_grizenko_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.03',
        'round' => '9',
        'eco' => 'A15',
        'white' => 'Тельманов Андрей',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'telmanov_gulinskiy_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.10',
        'round' => '11',
        'eco' => 'B20',
        'white' => 'Тельманов Андрей',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'telmanov_konoplev_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.20',
        'round' => '5',
        'eco' => 'A22',
        'white' => 'Тельманов Андрей',
        'black' => 'Коноплев Александр',
      ),
    ),
    'telmanov_leonov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.13',
        'round' => '3',
        'eco' => 'C00',
        'white' => 'Тельманов Андрей',
        'black' => 'Леонов Владимир',
      ),
    ),
    'telmanov_uglev_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.27',
        'round' => '7',
        'eco' => 'A24',
        'white' => 'Тельманов Андрей',
        'black' => 'Углев Эдуард',
      ),
    ),
    'tishenko_tishenko_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.22',
        'round' => '7',
        'eco' => 'B72',
        'white' => 'Тищенко Виктор',
        'black' => 'Тищенко Владимир',
      ),
    ),
    'tishenkovik_dedikov_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.27',
        'round' => '8',
        'eco' => 'D06',
        'white' => 'Тищенко Виктор',
        'black' => 'Дедиков Геннадий',
      ),
    ),
    'tishenkovik_djachenkokyr_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.05',
        'round' => '1',
        'eco' => 'D53',
        'white' => 'Тищенко Виктор',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'tishenkovik_djachenkokyr_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.08',
        'round' => '3',
        'eco' => 'B01',
        'white' => 'Тищенко Виктор',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'tishenkovik_grizenko_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.13',
        'round' => '4',
        'eco' => 'D93',
        'white' => 'Тищенко Виктор',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'tishenkovik_grizenko_2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2020',
        'date' => '2020.01.19',
        'round' => '3',
        'eco' => 'D85',
        'white' => 'Тищенко Виктор',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'tishenkovik_gulinskij_2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2020',
        'date' => '2020.02.02',
        'round' => '8',
        'eco' => 'D53',
        'white' => 'Тищенко Виктор',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'tishenkovik_irupin_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.01',
        'round' => '1',
        'eco' => 'C50',
        'white' => 'Тищенко Виктор',
        'black' => 'Ирюпин Андрей',
      ),
    ),
    'tishenkovik_leonov_2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2020',
        'date' => '2020.02.14',
        'round' => '10',
        'eco' => 'D53',
        'white' => 'Тищенко Виктор',
        'black' => 'Леонов Владимир',
      ),
    ),
    'tishenkovik_ligay_2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2020',
        'date' => '2020.01.11',
        'round' => '1',
        'eco' => 'A52',
        'white' => 'Тищенко Виктор',
        'black' => 'Лигай Руслан',
      ),
    ),
    'tishenkovik_rudv_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.06',
        'round' => '2',
        'eco' => 'A85',
        'white' => 'Тищенко Виктор',
        'black' => 'Рудь Виктор',
      ),
    ),
    'tishenkovik_shelkovskiy_2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2020',
        'date' => '2020.01.26',
        'round' => '6',
        'eco' => 'B13',
        'white' => 'Тищенко Виктор',
        'black' => 'Шелковский Артем',
      ),
    ),
    'tishenkovik_sudnizyn_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.10',
        'round' => '12',
        'eco' => 'D16',
        'white' => 'Тищенко Виктор',
        'black' => 'Судницын Николай',
      ),
    ),
    'tishenkovik_zelyak_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.15',
        'round' => '5',
        'eco' => 'B07',
        'white' => 'Тищенко Виктор',
        'black' => 'Зеляк Александр',
      ),
    ),
    'tishenkovik_zobnin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.20',
        'round' => '6',
        'eco' => 'D45',
        'white' => 'Тищенко Виктор',
        'black' => 'Зобнин Валентин',
      ),
    ),
    'tishenkovld_dudnik_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.23',
        'round' => '8',
        'eco' => 'D66',
        'white' => 'Тищенко Владимир',
        'black' => 'Дудник Татьяна',
      ),
    ),
    'tishenkovld_kotlyarov_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.02',
        'round' => '2',
        'eco' => 'E87',
        'white' => 'Тищенко Владимир',
        'black' => 'Котляров Егор',
      ),
    ),
    'tishenkovld_oganesyananna_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.23',
        'round' => '5',
        'eco' => 'E89',
        'white' => 'Тищенко Владимир',
        'black' => 'Оганесян Анна',
      ),
    ),
    'tishenkovld_shelkovskiy_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.16',
        'round' => '3',
        'eco' => 'D32',
        'white' => 'Тищенко Владимир',
        'black' => 'Шелковский Артем',
      ),
    ),
    'uglev_djachenkoserg_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.07',
        'round' => '2',
        'eco' => 'B72',
        'white' => 'Углев Эдуард',
        'black' => 'Дьяченко Сергей',
      ),
    ),
    'uglev_irupin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.21',
        'round' => '6',
        'eco' => 'C41',
        'white' => 'Углев Эдуард',
        'black' => 'Ирюпин Андрей',
      ),
    ),
    'uglev_konoplev_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.04',
        'round' => '10',
        'eco' => 'C80',
        'white' => 'Углев Эдуард',
        'black' => 'Коноплев Александр',
      ),
    ),
    'uglev_leonov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.28',
        'round' => '8',
        'eco' => 'C15',
        'white' => 'Углев Эдуард',
        'black' => 'Леонов Владимир',
      ),
    ),
    'uglev_makarov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.14',
        'round' => '4',
        'eco' => 'B02',
        'white' => 'Углев Эдуард',
        'black' => 'Макаров Валентин',
      ),
    ),
    'ustinov_kotlyarov_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.09',
        'round' => '1',
        'eco' => 'D07',
        'white' => 'Устинов Александр',
        'black' => 'Котляров Егор',
      ),
    ),
    'ustinov_nikolaev_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.23',
        'round' => '5',
        'eco' => 'D53',
        'white' => 'Устинов Александр',
        'black' => 'Николаев Никита',
      ),
    ),
    'ustinov_zelyak_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.16',
        'round' => '3',
        'eco' => 'A21',
        'white' => 'Устинов Александр',
        'black' => 'Зеляк Александр',
      ),
    ),
    'volginalex_djachenkokyr_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.28',
        'round' => '8',
        'eco' => 'C64',
        'white' => 'Волгин Александр',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'volginalex_gulinskiy_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.14',
        'round' => '4',
        'eco' => 'B52',
        'white' => 'Волгин Александр',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'volginalex_moskalenko_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.01',
        'round' => '1',
        'eco' => 'C68',
        'white' => 'Волгин Александр',
        'black' => 'Москаленко Игорь',
      ),
    ),
    'volginalex_oganesyananna_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.22',
        'round' => '7',
        'eco' => 'C77',
        'white' => 'Волгин Александр',
        'black' => 'Оганесян Анна',
      ),
    ),
    'volginalex_rudv_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.13',
        'round' => '3',
        'eco' => 'B06',
        'white' => 'Волгин Александр',
        'black' => 'Рудь Виктор',
      ),
    ),
    'volginalex_shirinyan_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.21',
        'round' => '6',
        'eco' => 'C66',
        'white' => 'Волгин Александр',
        'black' => 'Ширинян Вазир',
      ),
    ),
    'volginalex_sudnizyn_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.11',
        'round' => '12',
        'eco' => 'B13',
        'white' => 'Волгин Александр',
        'black' => 'Судницын Николай',
      ),
    ),
    'volginalex_telmanov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.04',
        'round' => '10',
        'eco' => 'B23',
        'white' => 'Волгин Александр',
        'black' => 'Тельманов Андрей',
      ),
    ),
    'volginalex_zabobonin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.06',
        'round' => '1',
        'eco' => 'C14',
        'white' => 'Волгин Александр',
        'black' => 'Забобонин Сергей',
      ),
    ),
    'volginalex_zelyak_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.08',
        'round' => '3',
        'eco' => 'B06',
        'white' => 'Волгин Александр',
        'black' => 'Зеляк Александр',
      ),
    ),
    'volginalex_zobnin_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.18',
        'round' => '14',
        'eco' => 'C78',
        'white' => 'Волгин Александр',
        'black' => 'Зобнин Валентин',
      ),
    ),
    'zabobonin_djachenkokyr_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.21',
        'round' => '6',
        'eco' => 'D11',
        'white' => 'Забобонин Сергей',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'zabobonin_dudnik_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.27',
        'round' => '8',
        'eco' => 'E06',
        'white' => 'Забобонин Сергей',
        'black' => 'Дудник Татьяна',
      ),
    ),
    'zabobonin_grechkin_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.13',
        'round' => '4',
        'eco' => 'D93',
        'white' => 'Забобонин Сергей',
        'black' => 'Гречкин Евгений',
      ),
    ),
    'zabobonin_grizenko_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.24',
        'round' => '15',
        'eco' => 'D85',
        'white' => 'Забобонин Сергей',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'zabobonin_gulinskiy_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.07',
        'round' => '2',
        'eco' => 'E01',
        'white' => 'Забобонин Сергей',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'zabobonin_gulinskiy_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.06',
        'round' => '2',
        'eco' => 'E01',
        'white' => 'Забобонин Сергей',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'zabobonin_telmanov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.28',
        'round' => '8',
        'eco' => 'B38',
        'white' => 'Забобонин Сергей',
        'black' => 'Тельманов Андрей',
      ),
    ),
    'zabobonin_tishenkovik_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.03',
        'round' => '13',
        'eco' => 'D43',
        'white' => 'Забобонин Сергей',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'zabobonin_tishenkovik_2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2020',
        'date' => '2020.01.25',
        'round' => '5',
        'eco' => 'E91',
        'white' => 'Забобонин Сергей',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'zelyak_konoplev_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.09',
        'round' => '1',
        'eco' => 'C45',
        'white' => 'Зеляк Александр',
        'black' => 'Коноплев Александр',
      ),
    ),
    'zelyak_oganesyananna_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.12.01',
        'round' => '8',
        'eco' => 'C45',
        'white' => 'Зеляк Александр',
        'black' => 'Оганесян Анна',
      ),
    ),
    'zelyak_ogansyanarsh_pf2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.09',
        'round' => '4',
        'eco' => 'C45',
        'white' => 'Зеляк Александр',
        'black' => 'Оганесян Аршак',
      ),
    ),
    'zelyak_skorikov_122018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2019',
        'date' => '2018.12.16',
        'round' => '6',
        'eco' => 'C68',
        'white' => 'Зеляк Александр',
        'black' => 'Скориков Александр',
      ),
    ),
    'zelyak_tishenkovik_2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2020',
        'date' => '2020.02.01',
        'round' => '7',
        'eco' => 'C14',
        'white' => 'Зеляк Александр',
        'black' => 'Тищенко Виктор',
      ),
    ),
    'zelyak_tishenkovld_pf2020.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Полуфинал Чемпионата города 2020',
        'date' => '2019.11.24',
        'round' => '6',
        'eco' => 'B72',
        'white' => 'Зеляк Александр',
        'black' => 'Тищенко Владимир',
      ),
    ),
    'zobnin_djachenkokyr_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.09',
        'round' => '11',
        'eco' => 'C02',
        'white' => 'Зобнин Валентин',
        'black' => 'Дьяченко Кирилл',
      ),
    ),
    'zobnin_dudnik_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.01.05',
        'round' => '1',
        'eco' => 'A36',
        'white' => 'Зобнин Валентин',
        'black' => 'Дудник Татьяна',
      ),
    ),
    'zobnin_grizenko_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.17',
        'round' => '13',
        'eco' => 'A36',
        'white' => 'Зобнин Валентин',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'zobnin_grizenko_2019.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2019',
        'date' => '2019.02.02',
        'round' => '9',
        'eco' => 'A36',
        'white' => 'Зобнин Валентин',
        'black' => 'Гриценко Сергей',
      ),
    ),
    'zobnin_gulinskiy_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.24',
        'round' => '15',
        'eco' => 'A36',
        'white' => 'Зобнин Валентин',
        'black' => 'Гулинский Владимир',
      ),
    ),
    'zobnin_shirinyan_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.07',
        'round' => '2',
        'eco' => 'A36',
        'white' => 'Зобнин Валентин',
        'black' => 'Ширинян Вазир',
      ),
    ),
    'zobnin_telmanov_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.01.21',
        'round' => '6',
        'eco' => 'A36',
        'white' => 'Зобнин Валентин',
        'black' => 'Тельманов Андрей',
      ),
    ),
    'zobnin_uglev_2018.pgn' => 
    array (
      0 => 
      array (
        'site' => 'Батайск',
        'event' => 'Чемпионат города 2018',
        'date' => '2018.02.10',
        'round' => '11',
        'eco' => 'C55',
        'white' => 'Зобнин Валентин',
        'black' => 'Углев Эдуард',
      ),
    ),
  ),
  'name' => 
  array (
    'Абрамов Кирилл' => 
    array (
      0 => 'konoplev_abramov_pf2020.pgn/0',
    ),
    'Алехин Александр' => 
    array (
      0 => 'Capablanca_Alekhine_1927_1.pgn/0',
      1 => 'Alekhine_Capablanca_1927_34.pgn/0',
      2 => 'Alekhine_Bogoljubow_1929_1.pgn/0',
      3 => 'Alekhine_Bogoljubow_1929_25.pgn/0',
      4 => 'Bogoljubow_Alekhine_1934_1.pgn/0',
      5 => 'Alekhine_Bogoljubow_1934_26.pgn/0',
      6 => 'Alekhine_Euwe_1935_1.pgn/0',
      7 => 'Euwe_Alekhine_1935_30.pgn/0',
      8 => 'Euwe_Alekhine_1937_1.pgn/0',
      9 => 'Euwe_Alekhine_1937_25.pgn/0',
    ),
    'Ананд Вишванатан' => 
    array (
      0 => 'Kasparov_Anand_1995.pgn/0',
    ),
    'Андерсен Адольф' => 
    array (
      0 => 'Anderssen_Kieseritzky_1851.pgn/0',
      1 => 'Morphy_Anderssen_1858.pgn/0',
      2 => 'Morphy_Anderssen_1858_13.pgn/0',
    ),
    'Ардашев Артем' => 
    array (
      0 => 'oganesyanarsh_arashev_pf2020.pgn/0',
      1 => 'ardashev_ustinov_pf2020.pgn/0',
      2 => 'konoplev_ardashev_pf2020.pgn/0',
      3 => 'ardashev_shelkovskiy_pf2020.pgn/0',
      4 => 'ardashev_ligay_pf2020.pgn/0',
      5 => 'skorikov_ardashev_pf2020.pgn/0',
      6 => 'ardashev_ligay_2020.pgn/0',
      7 => 'ardashev_tishenkovik_2020.pgn/0',
    ),
    'Боголюбов Ефим' => 
    array (
      0 => 'Alekhine_Bogoljubow_1929_1.pgn/0',
      1 => 'Alekhine_Bogoljubow_1929_25.pgn/0',
      2 => 'Bogoljubow_Alekhine_1934_1.pgn/0',
      3 => 'Alekhine_Bogoljubow_1934_26.pgn/0',
    ),
    'Ботвинник Михаил' => 
    array (
      0 => 'Botvinnik_Euwe_1948.pgn/0',
      1 => 'Botvinnik_Bronstein_1951_1.pgn/0',
      2 => 'Bronstein_Botvinnik_1951_24.pgn/0',
      3 => 'Smyslov_Botvinnik_1954_1.pgn/0',
      4 => 'Botvinnik_Smyslov_1954_24.pgn/0',
      5 => 'Botvinnik_Smyslov_1957_1.pgn/0',
      6 => 'Smyslov_Botvinnik_1957_22.pgn/0',
      7 => 'Smyslov_Botvinnik_1958_1.pgn/0',
      8 => 'Smyslov_Botvinnik_1958_23.pgn/0',
      9 => 'Tal_Botvinnik_1960_1.pgn/0',
      10 => 'Tal_Botvinnik_1960_21.pgn/0',
      11 => 'Botvinnik_Tal_1961_1.pgn/0',
      12 => 'Botvinnik_Tal_1961_21.pgn/0',
      13 => 'Petrosian_Botvinnik_1963_1.pgn/0',
      14 => 'Botvinnik_Petrosian_1963_22.pgn/0',
    ),
    'Бронштейн Давид' => 
    array (
      0 => 'Botvinnik_Bronstein_1951_1.pgn/0',
      1 => 'Bronstein_Botvinnik_1951_24.pgn/0',
    ),
    'Волгин Александр' => 
    array (
      0 => 'volginalex_zabobonin_2018.pgn/0',
      1 => 'grizenko_volginalex_2018.pgn/0',
      2 => 'volginalex_rudv_2018.pgn/0',
      3 => 'volginalex_gulinskiy_2018.pgn/0',
      4 => 'djachenkoserg_volginalex_2018.pgn/0',
      5 => 'volginalex_shirinyan_2018.pgn/0',
      6 => 'makarov_volginalex_2018.pgn/0',
      7 => 'volginalex_djachenkokyr_2018.pgn/0',
      8 => 'irupin_volginalex_2018.pgn/0',
      9 => 'volginalex_telmanov_2018.pgn/0',
      10 => 'leonov_volginalex_2018.pgn/0',
      11 => 'volginalex_sudnizyn_2018.pgn/0',
      12 => 'konoplev_volginalex_2018.pgn/0',
      13 => 'volginalex_zobnin_2018.pgn/0',
      14 => 'volginalex_moskalenko_pf2019.pgn/0',
      15 => 'dedikov_volginalex_pf2019.pgn/0',
      16 => 'volginalex_zelyak_pf2019.pgn/0',
      17 => 'irupin_volginalex_pf2019.pgn/0',
      18 => 'volginalex_oganesyananna_pf2019.pgn/0',
    ),
    'Гречкин Евгений' => 
    array (
      0 => 'moskalenko_grechkin_pf2019.pgn/0',
      1 => 'grechkin_skorikov_pf2019.pgn/0',
      2 => 'grechkin_samsonov_pf2019.pgn/0',
      3 => 'djachenkokyr_grechkin_pf2019.pgn/0',
      4 => 'dudnik_grechkin_122018.pgn/0',
      5 => 'grechkin_tishnkovik_pf2019.pgn/0',
      6 => 'shelkovski_grechkin_122018.pgn/0',
      7 => 'grechkin_samsonov_2019.pgn/0',
      8 => 'zabobonin_grechkin_2019.pgn/0',
      9 => 'grechkin_tishenkovik_2019.pgn/0',
      10 => 'grechkin_gulinskiy_2019.pgn/0',
      11 => 'grizenko_grechkin_2019.pgn/0',
      12 => 'grechkin_jachenkokyr_2019.pgn/0',
      13 => 'grechkin_zobnin_2019.pgn/0',
      14 => 'leonov_grechkin_2019.pgn/0',
      15 => 'grechkin_dedikov_2019.pgn/0',
      16 => 'dudnik_grechkin_2019.pgn/0',
      17 => 'grechkin_tishenkovik_2020.pgn/0',
    ),
    'Гриценко Сергей' => 
    array (
      0 => 'grizenko_rudv_2018.pgn/0',
      1 => 'grizenko_volginalex_2018.pgn/0',
      2 => 'grizenko_djachenkoserg_2018.pgn/0',
      3 => 'gulinskiy_grizenko_2018.pgn/0',
      4 => 'grizenko_makarov_2018.pgn/0',
      5 => 'djachenkokyr_grizenko_2018.pgn/0',
      6 => 'grizenko_irupin_2018.pgn/0',
      7 => 'telmanov_grizenko_2018.pgn/0',
      8 => 'grizenko_leonov_2018.pgn/0',
      9 => 'sudnizyn_grizenko_2018.pgn/0',
      10 => 'grizenko_konoplev_2018.pgn/0',
      11 => 'zobnin_grizenko_2018.pgn/0',
      12 => 'grizenko_uglev_2018.pgn/0',
      13 => 'zabobonin_grizenko_2018.pgn/0',
      14 => 'sudnizyn_grizenko_2019.pgn/0',
      15 => 'grizenko_zabobonin_2019.pgn/0',
      16 => 'tishenkovik_grizenko_2019.pgn/0',
      17 => 'gulinskiy_grizenko_2019.pgn/0',
      18 => 'grizenko_djachenkokyr_2019.pgn/0',
      19 => 'grizenko_grechkin_2019.pgn/0',
      20 => 'zobnin_grizenko_2019.pgn/0',
      21 => 'grizenko_leonov_2019.pgn/0',
      22 => 'dedikov_grizenko_2019.pgn/0',
      23 => 'grizenko_dudnik_2019.pgn/0',
      24 => 'tishenkovik_grizenko_2020.pgn/0',
    ),
    'Гулинский Владимир' => 
    array (
      0 => 'gulinskiy-uglev_06012018.pgn/0',
      1 => 'zabobonin_gulinskiy_2018.pgn/0',
      2 => 'volginalex_gulinskiy_2018.pgn/0',
      3 => 'gulinskiy_grizenko_2018.pgn/0',
      4 => 'gulinskiy_rudv_2018.pgn/0',
      5 => 'gulinskiy_djachenkoserg_2018.pgn/0',
      6 => 'shirinyan_gulinskiy_2018.pgn/0',
      7 => 'gulinskiy_makarov_2018.pgn/0',
      8 => 'djachenkokyr_gulinskiy_2018.pgn/0',
      9 => 'gulinskiy_irupin_2018.pgn/0',
      10 => 'telmanov_gulinskiy_2018.pgn/0',
      11 => 'gulinskiy_leonov_2018.pgn/0',
      12 => 'sudnizyn_gulinskiy_2018.pgn/0',
      13 => 'gulinskiy_konoplev_2018.pgn/0',
      14 => 'zobnin_gulinskiy_2018.pgn/0',
      15 => 'gulinskiy_sudnizyn_2019.pgn/0',
      16 => 'zabobonin_gulinskiy_2019.pgn/0',
      17 => 'gulinskiy_tishenkovik_2019.pgn/0',
      18 => 'rudv_gulinskiy_2019.pgn/0',
      19 => 'gulinskiy_djachenkokyr_2019.pgn/0',
      20 => 'gulinskiy_grizenko_2019.pgn/0',
      21 => 'grechkin_gulinskiy_2019.pgn/0',
      22 => 'gulinskiy_zobnin_2019.pgn/0',
      23 => 'gulinskiy_dedikov_2019.pgn/0',
      24 => 'dudnik_gulinskiy_2019.pgn/0',
      25 => 'leonov_gulinskiy_2019.pgn/0',
      26 => 'tishenkovik_gulinskij_2020.pgn/0',
    ),
    'Гунсберг Исидор' => 
    array (
      0 => 'Steinitz_Gunsberg_1890_1.pgn/0',
      1 => 'Steinitz_Gunsberg_1891_19.pgn/0',
    ),
    'Дедиков Геннадий' => 
    array (
      0 => 'dedikov_volginalex_pf2019.pgn/0',
      1 => 'oganesyanarsh_dedikov_pf2019.pgn/0',
      2 => 'dedikov_tishenkovik_122018.pgn/0',
      3 => 'dedikov_djachenkokyr_122018.pgn/0',
      4 => 'dedikov_shelkovskiy_pf2019.pgn/0',
      5 => 'irupin_dedikov_pf2019.pgn/0',
      6 => 'djachenkokyr_dedikov_2019.pgn/0',
      7 => 'leonov_dedikov_2019.pgn/0',
      8 => 'dedikov_dudnik_2019.pgn/0',
      9 => 'samsonov_dedikov_2019.pgn/0',
      10 => 'sudnizyn_dedikov_2019.pgn/0',
      11 => 'dedikov_zabobonin_2019.pgn/0',
      12 => 'tishenkovik_dedikov_2019.pgn/0',
      13 => 'gulinskiy_dedikov_2019.pgn/0',
      14 => 'dedikov_grizenko_2019.pgn/0',
      15 => 'grechkin_dedikov_2019.pgn/0',
    ),
    'Демьянченко Валерий' => 
    array (
      0 => 'samsonov_demjanchenko_122018.pgn/0',
      1 => 'demjanchenko_dudnik_pf2019.pgn/0',
    ),
    'Дудник Татьяна' => 
    array (
      0 => 'dudnik_zelyak_122018.pgn/0',
      1 => 'demjanchenko_dudnik_pf2019.pgn/0',
      2 => 'dudnik_shelkovskiy_pf2019.pgn/0',
      3 => 'dudnik_tishenkovik_pf2019.pgn/0',
      4 => 'dudnik_grechkin_122018.pgn/0',
      5 => 'tishenkovld_dudnik_pf2019.pgn/0',
      6 => 'djachenkokyr_dudnik_pf2019.pgn/0',
      7 => 'zobnin_dudnik_2019.pgn/0',
      8 => 'dedikov_dudnik_2019.pgn/0',
      9 => 'djachenkokyr_dudnik_2019.pgn/0',
      10 => 'dudnik_samsonov_2019.pgn/0',
      11 => 'dudnik_sudnizyn_2019.pgn/0',
      12 => 'zabobonin_dudnik_2019.pgn/0',
      13 => 'dudnik_tishenkovik_2019.pgn/0',
      14 => 'dudnik_gulinskiy_2019.pgn/0',
      15 => 'grizenko_dudnik_2019.pgn/0',
      16 => 'dudnik_grechkin_2019.pgn/0',
    ),
    'Дьяченко Кирилл' => 
    array (
      0 => 'djachenkokyr_leonov_2018.pgn/0',
      1 => 'sudnizyn_djachenkokyr_2018.pgn/0',
      2 => 'zabobonin_djachenkokyr_2018.pgn/0',
      3 => 'djachenkokyr_grizenko_2018.pgn/0',
      4 => 'volginalex_djachenkokyr_2018.pgn/0',
      5 => 'djachenkokyr_gulinskiy_2018.pgn/0',
      6 => 'djachenkoserg_djachenkokyr_2018.pgn/0',
      7 => 'makarov_djachenkokyr_2018.pgn/0',
      8 => 'telmanov_djachnkokyr_2018.pgn/0',
      9 => 'tishenkovik_djachenkokyr_pf2019.pgn/0',
      10 => 'djachenkokyr_grechkin_pf2019.pgn/0',
      11 => 'dedikov_djachenkokyr_122018.pgn/0',
      12 => 'djachenkokyr_samsonov_pf2019.pgn/0',
      13 => 'irupin_djachenkokyr_pf2019.pgn/0',
      14 => 'djachenkokyr_dudnik_pf2019.pgn/0',
      15 => 'tishenkovik_djachenkokyr_2019.pgn/0',
      16 => 'djachenkokyr_dedikov_2019.pgn/0',
      17 => 'rudv_djachenkokyr_2019.pgn/0',
      18 => 'djachenkokyr_dudnik_2019.pgn/0',
      19 => 'gulinskiy_djachenkokyr_2019.pgn/0',
      20 => 'djachenkokyr_samsonov_2019.pgn/0',
      21 => 'grizenko_djachenkokyr_2019.pgn/0',
      22 => 'grechkin_jachenkokyr_2019.pgn/0',
      23 => 'djachenkokyr_sudnizyn_2019.pgn/0',
      24 => 'zobnin_djachenkokyr_2019.pgn/0',
      25 => 'djachenkokyr_zabobonin_2019.pgn/0',
      26 => 'leonov_djachenkokyr_2019.pgn/0',
    ),
    'Дьяченко Сергей' => 
    array (
      0 => 'djachenkoserg-zobnin_06012018.pgn/0',
      1 => 'uglev_djachenkoserg_2018.pgn/0',
      2 => 'djachenkoserg_zabobonin_2018.pgn/0',
      3 => 'grizenko_djachenkoserg_2018.pgn/0',
      4 => 'djachenkoserg_volginalex_2018.pgn/0',
      5 => 'gulinskiy_djachenkoserg_2018.pgn/0',
      6 => 'djachenkoserg_rudv_2018.pgn/0',
      7 => 'makarov_djachenkoserg_2018.pgn/0',
      8 => 'djachenkoserg_djachenkokyr_2018.pgn/0',
      9 => 'irupin_djachenkoserg_2018.pgn/0',
      10 => 'djachenkoserg_telmanov_2018.pgn/0',
      11 => 'leonov_djachenkserg_2018.pgn/0',
      12 => 'djachenkoserg_sudnizyn_2018.pgn/0',
      13 => 'konoplev_djachenkoserg_2018.pgn/0',
    ),
    'Забобонин Сергей' => 
    array (
      0 => 'volginalex_zabobonin_2018.pgn/0',
      1 => 'zabobonin_gulinskiy_2018.pgn/0',
      2 => 'djachenkoserg_zabobonin_2018.pgn/0',
      3 => 'zabobonin_djachenkokyr_2018.pgn/0',
      4 => 'irupin_zabobonin_2018.pgn/0',
      5 => 'zabobonin_telmanov_2018.pgn/0',
      6 => 'rudv_zabobonin_2018.pgn/0',
      7 => 'zabobonin_grizenko_2018.pgn/0',
      8 => 'rudv_zabobonin_2019.pgn/0',
      9 => 'zabobonin_gulinskiy_2019.pgn/0',
      10 => 'grizenko_zabobonin_2019.pgn/0',
      11 => 'zabobonin_grechkin_2019.pgn/0',
      12 => 'dedikov_zabobonin_2019.pgn/0',
      13 => 'zabobonin_dudnik_2019.pgn/0',
      14 => 'zabobonin_tishenkovik_2019.pgn/0',
      15 => 'sudnizyn_zabobonin_2019.pgn/0',
      16 => 'djachenkokyr_zabobonin_2019.pgn/0',
      17 => 'zabobonin_tishenkovik_2020.pgn/0',
    ),
    'Зеляк Александр' => 
    array (
      0 => 'dudnik_zelyak_122018.pgn/0',
      1 => 'volginalex_zelyak_pf2019.pgn/0',
      2 => 'zelyak_ogansyanarsh_pf2019.pgn/0',
      3 => 'tishenkovik_zelyak_pf2019.pgn/0',
      4 => 'zelyak_skorikov_122018.pgn/0',
      5 => 'kotlyarov_zelyak_122018.pgn/0',
      6 => 'samsonov_zelyak_pf2019.pgn/0',
      7 => 'zelyak_konoplev_pf2020.pgn/0',
      8 => 'ustinov_zelyak_pf2020.pgn/0',
      9 => 'zelyak_tishenkovld_pf2020.pgn/0',
      10 => 'zelyak_oganesyananna_2019.pgn/0',
      11 => 'palladin_zelyak_pf2020.pgn/0',
      12 => 'zelyak_tishenkovik_2020.pgn/0',
    ),
    'Зобнин Валентин' => 
    array (
      0 => 'djachenkoserg-zobnin_06012018.pgn/0',
      1 => 'zobnin_shirinyan_2018.pgn/0',
      2 => 'irupin_zobnin_2018.pgn/0',
      3 => 'zobnin_telmanov_2018.pgn/0',
      4 => 'rudv_zobnin_2018.pgn/0',
      5 => 'zobnin_uglev_2018.pgn/0',
      6 => 'zobnin_grizenko_2018.pgn/0',
      7 => 'volginalex_zobnin_2018.pgn/0',
      8 => 'zobnin_gulinskiy_2018.pgn/0',
      9 => 'zobnin_dudnik_2019.pgn/0',
      10 => 'samsonov_zobnin_2019.pgn/0',
      11 => 'tishenkovik_zobnin_2019.pgn/0',
      12 => 'gulinskiy_zobnin_2019.pgn/0',
      13 => 'zobnin_grizenko_2019.pgn/0',
      14 => 'grechkin_zobnin_2019.pgn/0',
      15 => 'zobnin_djachenkokyr_2019.pgn/0',
    ),
    'Ирюпин Андрей' => 
    array (
      0 => 'irupin_telmanov_2018.pgn/0',
      1 => 'leonov_irupin_2018.pgn/0',
      2 => 'irupin_sudnizyn_2018.pgn/0',
      3 => 'konoplev_irupin_2018.pgn/0',
      4 => 'irupin_zobnin_2018.pgn/0',
      5 => 'uglev_irupin_2018.pgn/0',
      6 => 'irupin_zabobonin_2018.pgn/0',
      7 => 'grizenko_irupin_2018.pgn/0',
      8 => 'irupin_volginalex_2018.pgn/0',
      9 => 'gulinskiy_irupin_2018.pgn/0',
      10 => 'irupin_djachenkoserg_2018.pgn/0',
      11 => 'irupin_makarov_2018.pgn/0',
      12 => 'irupin_rudv_2018.pgn/0',
      13 => 'tishenkovik_irupin_pf2019.pgn/0',
      14 => 'irupin_oganesyananna_pf2019.pgn/0',
      15 => 'kotlyarov_irupin_pf2019.pgn/0',
      16 => 'irupin_volginalex_pf2019.pgn/0',
      17 => 'shelkovskij_irupin_pf2019.pgn/0',
      18 => 'irupin_oganesyanarsh_pf2019.pgn/0',
      19 => 'irupin_djachenkokyr_pf2019.pgn/0',
      20 => 'irupin_dedikov_pf2019.pgn/0',
    ),
    'Капабланка Хосе Рауль' => 
    array (
      0 => 'Capablanca_Lasker_1921_1.pgn/0',
      1 => 'Lasker_Capablanca_1921_14.pgn/0',
      2 => 'Capablanca_Alekhine_1927_1.pgn/0',
      3 => 'Alekhine_Capablanca_1927_34.pgn/0',
    ),
    'Карпов Анатолий' => 
    array (
      0 => 'Kortschnoj_Karpov_1978_1.pgn/0',
      1 => 'Karpov_Kortschnoj_1978_32.pgn/0',
      2 => 'Kortschnoj_Karpov_1981_1.pgn/0',
      3 => 'Karpov_Kortschnoj_1981_18.pgn/0',
      4 => 'Karpov_Kasparov_1984_1.pgn/0',
      5 => 'Kasparov_Karpov_1985_48.pgn/0',
    ),
    'Каспаров Гарри' => 
    array (
      0 => 'Karpov_Kasparov_1984_1.pgn/0',
      1 => 'Kasparov_Karpov_1985_48.pgn/0',
      2 => 'Kasparov_Anand_1995.pgn/0',
    ),
    'Керес Пауль' => 
    array (
      0 => 'Euwe_Keres_1948_1.pgn/0',
    ),
    'Кизерицкий Лионель' => 
    array (
      0 => 'Anderssen_Kieseritzky_1851.pgn/0',
    ),
    'Коноплев Александр' => 
    array (
      0 => 'shirinnyan_konoplev_2018.pgn/0',
      1 => 'konoplev_makarov_2018.pgn/0',
      2 => 'konoplev_irupin_2018.pgn/0',
      3 => 'telmanov_konoplev_2018.pgn/0',
      4 => 'uglev_konoplev_2018.pgn/0',
      5 => 'grizenko_konoplev_2018.pgn/0',
      6 => 'konoplev_volginalex_2018.pgn/0',
      7 => 'gulinskiy_konoplev_2018.pgn/0',
      8 => 'konoplev_djachenkoserg_2018.pgn/0',
      9 => 'zelyak_konoplev_pf2020.pgn/0',
      10 => 'konoplev_abramov_pf2020.pgn/0',
      11 => 'konoplev_ardashev_pf2020.pgn/0',
      12 => 'skorikov_konoplev_pf2020.pgn/0',
      13 => 'konoplev_palladin_pf2020.pgn/0',
      14 => 'ligay_konoplev_pf2020.pgn/0',
      15 => 'konoplev_nikolaev_pf2020.pgn/0',
    ),
    'Корчной Виктор' => 
    array (
      0 => 'Kortschnoj_Karpov_1978_1.pgn/0',
      1 => 'Karpov_Kortschnoj_1978_32.pgn/0',
      2 => 'Kortschnoj_Karpov_1981_1.pgn/0',
      3 => 'Karpov_Kortschnoj_1981_18.pgn/0',
    ),
    'Котляров Егор' => 
    array (
      0 => 'kotlyarov_samsonov_pf2019.pgn/0',
      1 => 'tishenkovld_kotlyarov_pf2019.pgn/0',
      2 => 'kotlyarov_irupin_pf2019.pgn/0',
      3 => 'kotlyarov_zelyak_122018.pgn/0',
      4 => 'ustinov_kotlyarov_pf2020.pgn/0',
    ),
    'Ласкер Эмануил' => 
    array (
      0 => 'Lasker_Steinitz_1894_1.pgn/0',
      1 => 'Lasker_Steinitz_1894_19.pgn/0',
      2 => 'Steinitz_Lasker_1896_1.pgn/0',
      3 => 'Steinitz_Lasker_1897_17.pgn/0',
      4 => 'Marshall_Lasker_1907_1.pgn/0',
      5 => 'Marshall_Lasker_1907_15.pgn/0',
      6 => 'Lasker_Tarrasch_1908_1.pgn/0',
      7 => 'Tarrasch_Lasker_1908_16.pgn/0',
      8 => 'Lasker_Janowski_1909_1.pgn/0',
      9 => 'Janowski_Lasker_1909_10.pgn/0',
      10 => 'Schlechter_Lasker_1910_1.pgn/0',
      11 => 'Lasker_Schlechter_1910_10.pgn/0',
      12 => 'Lasker_Janowski_1910_1.pgn/0',
      13 => 'Lasker_Janowski_1910_11.pgn/0',
      14 => 'Capablanca_Lasker_1921_1.pgn/0',
      15 => 'Lasker_Capablanca_1921_14.pgn/0',
    ),
    'Леонов Владимир' => 
    array (
      0 => 'djachenkokyr_leonov_2018.pgn/0',
      1 => 'leonov_irupin_2018.pgn/0',
      2 => 'telmanov_leonov_2018.pgn/0',
      3 => 'leonov_sudnizyn_2018.pgn/0',
      4 => 'uglev_leonov_2018.pgn/0',
      5 => 'grizenko_leonov_2018.pgn/0',
      6 => 'leonov_volginalex_2018.pgn/0',
      7 => 'gulinskiy_leonov_2018.pgn/0',
      8 => 'leonov_djachenkserg_2018.pgn/0',
      9 => 'leonov_dedikov_2019.pgn/0',
      10 => 'leonov_tishnkovik_2019.pgn/0',
      11 => 'leonov_sudnizyn_2019.pgn/0',
      12 => 'grizenko_leonov_2019.pgn/0',
      13 => 'leonov_grechkin_2019.pgn/0',
      14 => 'leonov_gulinskiy_2019.pgn/0',
      15 => 'leonov_djachenkokyr_2019.pgn/0',
      16 => 'tishenkovik_leonov_2020.pgn/0',
    ),
    'Лигай Руслан' => 
    array (
      0 => 'shelkovskiy_ligay_pf2020.pgn/0',
      1 => 'ligay_skorikov_pf2020.pgn/0',
      2 => 'palladin_ligay_pf2020.pgn/0',
      3 => 'ligay_konoplev_pf2020.pgn/0',
      4 => 'ardashev_ligay_pf2020.pgn/0',
      5 => 'ligay_ustinov_pf2020.pgn/0',
      6 => 'tishenkovik_ligay_2020.pgn/0',
      7 => 'ardashev_ligay_2020.pgn/0',
    ),
    'Локтионов Максим' => 
    array (
      0 => 'loktionov_shlkovskiy_pf2020.pgn/0',
    ),
    'Макаров Валентин' => 
    array (
      0 => 'makarovv_sudnizynn_2018.pgn/0',
      1 => 'konoplev_makarov_2018.pgn/0',
      2 => 'uglev_makarov_2018.pgn/0',
      3 => 'grizenko_makarov_2018.pgn/0',
      4 => 'makarov_volginalex_2018.pgn/0',
      5 => 'gulinskiy_makarov_2018.pgn/0',
      6 => 'makarov_djachenkoserg_2018.pgn/0',
      7 => 'makarov_rudv_2018.pgn/0',
      8 => 'makarov_djachenkokyr_2018.pgn/0',
      9 => 'irupin_makarov_2018.pgn/0',
      10 => 'makarov_telmanov_2018.pgn/0',
    ),
    'Маршалл Фрэнк' => 
    array (
      0 => 'Marshall_Lasker_1907_1.pgn/0',
      1 => 'Marshall_Lasker_1907_15.pgn/0',
    ),
    'Морфи Пол' => 
    array (
      0 => 'Morphy_Isouard_1858.pgn/0',
      1 => 'Morphy_Anderssen_1858.pgn/0',
      2 => 'Morphy_Anderssen_1858_13.pgn/0',
    ),
    'Москаленко Игорь' => 
    array (
      0 => 'volginalex_moskalenko_pf2019.pgn/0',
      1 => 'moskalenko_grechkin_pf2019.pgn/0',
      2 => 'oganesyanan_moskalenko_122018.pgn/0',
      3 => 'shelkovskiy_moskalenko_pf2019.pgn/0',
    ),
    'Николаев Никита' => 
    array (
      0 => 'skorikov_nikolaev_pf2020.pgn/0',
      1 => 'nikolaev_tishenkovld_pf2020.pgn/0',
      2 => 'ustinov_nikolaev_pf2020.pgn/0',
      3 => 'konoplev_nikolaev_pf2020.pgn/0',
    ),
    'Оганесян Анна' => 
    array (
      0 => 'oganesyananna_skorikov_pf2019.pgn/0',
      1 => 'irupin_oganesyananna_pf2019.pgn/0',
      2 => 'oganesyanan_moskalenko_122018.pgn/0',
      3 => 'volginalex_oganesyananna_pf2019.pgn/0',
      4 => 'samsonov_oganesyananna_pf2019.pgn/0',
      5 => 'oganesyananna_ustinov_pf2020.pgn/0',
      6 => 'tishenkovld_oganesyananna_pf2020.pgn/0',
      7 => 'zelyak_oganesyananna_2019.pgn/0',
      8 => 'oganesyananna_shelkovskiy_pf2020.pgn/0',
    ),
    'Оганесян Аршак' => 
    array (
      0 => 'oganesyanarsh_dedikov_pf2019.pgn/0',
      1 => 'zelyak_ogansyanarsh_pf2019.pgn/0',
      2 => 'irupin_oganesyanarsh_pf2019.pgn/0',
      3 => 'oganesyanarsh_arashev_pf2020.pgn/0',
    ),
    'Палладин Дмитрий' => 
    array (
      0 => 'konoplev_palladin_pf2020.pgn/0',
      1 => 'palladin_ligay_pf2020.pgn/0',
      2 => 'palladin_zelyak_pf2020.pgn/0',
    ),
    'Петросян Тигран' => 
    array (
      0 => 'Petrosian_Botvinnik_1963_1.pgn/0',
      1 => 'Botvinnik_Petrosian_1963_22.pgn/0',
      2 => 'Spassky_Petrosian_1966_1.pgn/0',
      3 => 'Petrosian_Spassky_1966_24.pgn/0',
      4 => 'Spassky_Petrosian_1969_1.pgn/0',
      5 => 'Spassky_Petrosian_1969_23.pgn/0',
    ),
    'Решевский Самуэль' => 
    array (
      0 => 'Smyslov_Reshevsky_1948.pgn/0',
    ),
    'Рудь Виктор' => 
    array (
      0 => 'grizenko_rudv_2018.pgn/0',
      1 => 'rudv_telmanov_2018.pgn/0',
      2 => 'volginalex_rudv_2018.pgn/0',
      3 => 'gulinskiy_rudv_2018.pgn/0',
      4 => 'rudv_sudnizyn_2018.pgn/0',
      5 => 'djachenkoserg_rudv_2018.pgn/0',
      6 => 'rudv_zobnin_2018.pgn/0',
      7 => 'makarov_rudv_2018.pgn/0',
      8 => 'rudv_uglev_2018.pgn/0',
      9 => 'rudv_zabobonin_2018.pgn/0',
      10 => 'irupin_rudv_2018.pgn/0',
      11 => 'rudv_zabobonin_2019.pgn/0',
      12 => 'tishenkovik_rudv_2019.pgn/0',
      13 => 'rudv_djachenkokyr_2019.pgn/0',
      14 => 'rudv_gulinskiy_2019.pgn/0',
    ),
    'Самсонов Евгений' => 
    array (
      0 => 'kotlyarov_samsonov_pf2019.pgn/0',
      1 => 'samsonov_demjanchenko_122018.pgn/0',
      2 => 'grechkin_samsonov_pf2019.pgn/0',
      3 => 'skorikov_samsonov_pf2019.pgn/0',
      4 => 'samsonov_shelkovskiy_pf2019.pgn/0',
      5 => 'djachenkokyr_samsonov_pf2019.pgn/0',
      6 => 'samsonov_zelyak_pf2019.pgn/0',
      7 => 'samsonov_oganesyananna_pf2019.pgn/0',
      8 => 'grechkin_samsonov_2019.pgn/0',
      9 => 'samsonov_zobnin_2019.pgn/0',
      10 => 'samsonov_dedikov_2019.pgn/0',
      11 => 'dudnik_samsonov_2019.pgn/0',
      12 => 'djachenkokyr_samsonov_2019.pgn/0',
    ),
    'Скориков Александр' => 
    array (
      0 => 'oganesyananna_skorikov_pf2019.pgn/0',
      1 => 'skorikov_tishenkovik_pf2018.pgn/0',
      2 => 'grechkin_skorikov_pf2019.pgn/0',
      3 => 'skorikov_samsonov_pf2019.pgn/0',
      4 => 'zelyak_skorikov_122018.pgn/0',
      5 => 'skorikov_tishenkovld_pf2019.pgn/0',
      6 => 'skorikov_nikolaev_pf2020.pgn/0',
      7 => 'skorikov_konoplev_pf2020.pgn/0',
      8 => 'ligay_skorikov_pf2020.pgn/0',
      9 => 'skorikov_ustinov_pf2020.pgn/0',
      10 => 'skorikov_ardashev_pf2020.pgn/0',
    ),
    'Смыслов Василий' => 
    array (
      0 => 'Smyslov_Reshevsky_1948.pgn/0',
      1 => 'Smyslov_Botvinnik_1954_1.pgn/0',
      2 => 'Botvinnik_Smyslov_1954_24.pgn/0',
      3 => 'Botvinnik_Smyslov_1957_1.pgn/0',
      4 => 'Smyslov_Botvinnik_1957_22.pgn/0',
      5 => 'Smyslov_Botvinnik_1958_1.pgn/0',
      6 => 'Smyslov_Botvinnik_1958_23.pgn/0',
    ),
    'Спасский Борис' => 
    array (
      0 => 'Spassky_Petrosian_1966_1.pgn/0',
      1 => 'Petrosian_Spassky_1966_24.pgn/0',
      2 => 'Spassky_Petrosian_1969_1.pgn/0',
      3 => 'Spassky_Petrosian_1969_23.pgn/0',
      4 => 'Spassky_Fischer_1972_1.pgn/0',
      5 => 'Spassky_Fischer_1972_21.pgn/0',
    ),
    'Стейниц Вильгельм' => 
    array (
      0 => 'Zukertort_Steinitz_1886_1.pgn/0',
      1 => 'Steinitz_Zukertort_1886_20.pgn/0',
      2 => 'Chigorin_Steinitz_1889_1.pgn/0',
      3 => 'Chigorin_Steinitz_1889_17.pgn/0',
      4 => 'Steinitz_Gunsberg_1890_1.pgn/0',
      5 => 'Steinitz_Gunsberg_1891_19.pgn/0',
      6 => 'Chigorin_Steinitz_1892_1.pgn/0',
      7 => 'Chigorin_Steinitz_1892_23.pgn/0',
      8 => 'Lasker_Steinitz_1894_1.pgn/0',
      9 => 'Lasker_Steinitz_1894_19.pgn/0',
      10 => 'Steinitz_Lasker_1896_1.pgn/0',
      11 => 'Steinitz_Lasker_1897_17.pgn/0',
    ),
    'Судницын Николай' => 
    array (
      0 => 'makarovv_sudnizynn_2018.pgn/0',
      1 => 'sudnizyn_djachenkokyr_2018.pgn/0',
      2 => 'irupin_sudnizyn_2018.pgn/0',
      3 => 'sudnizyn_telmanov_2018.pgn/0',
      4 => 'leonov_sudnizyn_2018.pgn/0',
      5 => 'rudv_sudnizyn_2018.pgn/0',
      6 => 'sudnizyn_uglev_2018.pgn/0',
      7 => 'sudnizyn_grizenko_2018.pgn/0',
      8 => 'volginalex_sudnizyn_2018.pgn/0',
      9 => 'sudnizyn_gulinskiy_2018.pgn/0',
      10 => 'djachenkoserg_sudnizyn_2018.pgn/0',
      11 => 'gulinskiy_sudnizyn_2019.pgn/0',
      12 => 'sudnizyn_grizenko_2019.pgn/0',
      13 => 'sudnizyn_dedikov_2019.pgn/0',
      14 => 'dudnik_sudnizyn_2019.pgn/0',
      15 => 'leonov_sudnizyn_2019.pgn/0',
      16 => 'djachenkokyr_sudnizyn_2019.pgn/0',
      17 => 'sudnizyn_zabobonin_2019.pgn/0',
      18 => 'tishenkovik_sudnizyn_2019.pgn/0',
    ),
    'Таль Михаил' => 
    array (
      0 => 'Tal_Botvinnik_1960_1.pgn/0',
      1 => 'Tal_Botvinnik_1960_21.pgn/0',
      2 => 'Botvinnik_Tal_1961_1.pgn/0',
      3 => 'Botvinnik_Tal_1961_21.pgn/0',
    ),
    'Тарраш Зигберт' => 
    array (
      0 => 'Lasker_Tarrasch_1908_1.pgn/0',
      1 => 'Tarrasch_Lasker_1908_16.pgn/0',
    ),
    'Тельманов Андрей' => 
    array (
      0 => 'irupin_telmanov_2018.pgn/0',
      1 => 'rudv_telmanov_2018.pgn/0',
      2 => 'telmanov_leonov_2018.pgn/0',
      3 => 'sudnizyn_telmanov_2018.pgn/0',
      4 => 'telmanov_konoplev_2018.pgn/0',
      5 => 'zobnin_telmanov_2018.pgn/0',
      6 => 'telmanov_uglev_2018.pgn/0',
      7 => 'zabobonin_telmanov_2018.pgn/0',
      8 => 'telmanov_grizenko_2018.pgn/0',
      9 => 'volginalex_telmanov_2018.pgn/0',
      10 => 'telmanov_gulinskiy_2018.pgn/0',
      11 => 'djachenkoserg_telmanov_2018.pgn/0',
      12 => 'makarov_telmanov_2018.pgn/0',
      13 => 'telmanov_djachnkokyr_2018.pgn/0',
    ),
    'Тищенко Виктор' => 
    array (
      0 => 'tishenkovik_irupin_pf2019.pgn/0',
      1 => 'skorikov_tishenkovik_pf2018.pgn/0',
      2 => 'tishenkovik_djachenkokyr_pf2019.pgn/0',
      3 => 'dedikov_tishenkovik_122018.pgn/0',
      4 => 'tishenkovik_zelyak_pf2019.pgn/0',
      5 => 'dudnik_tishenkovik_pf2019.pgn/0',
      6 => 'tishenko_tishenko_pf2019.pgn/0',
      7 => 'grechkin_tishnkovik_pf2019.pgn/0',
      8 => 'tishenkovik_djachenkokyr_2019.pgn/0',
      9 => 'tishenkovik_rudv_2019.pgn/0',
      10 => 'gulinskiy_tishenkovik_2019.pgn/0',
      11 => 'tishenkovik_grizenko_2019.pgn/0',
      12 => 'grechkin_tishenkovik_2019.pgn/0',
      13 => 'tishenkovik_zobnin_2019.pgn/0',
      14 => 'leonov_tishnkovik_2019.pgn/0',
      15 => 'tishenkovik_dedikov_2019.pgn/0',
      16 => 'dudnik_tishenkovik_2019.pgn/0',
      17 => 'zabobonin_tishenkovik_2019.pgn/0',
      18 => 'tishenkovik_sudnizyn_2019.pgn/0',
      19 => 'tishenkovik_ligay_2020.pgn/0',
      20 => 'grechkin_tishenkovik_2020.pgn/0',
      21 => 'tishenkovik_grizenko_2020.pgn/0',
      22 => 'zabobonin_tishenkovik_2020.pgn/0',
      23 => 'tishenkovik_shelkovskiy_2020.pgn/0',
      24 => 'zelyak_tishenkovik_2020.pgn/0',
      25 => 'tishenkovik_gulinskij_2020.pgn/0',
      26 => 'ardashev_tishenkovik_2020.pgn/0',
      27 => 'tishenkovik_leonov_2020.pgn/0',
    ),
    'Тищенко Владимир' => 
    array (
      0 => 'tishenkovld_kotlyarov_pf2019.pgn/0',
      1 => 'shelkovskiy_tishnkovld_pf2019.pgn/0',
      2 => 'tishenko_tishenko_pf2019.pgn/0',
      3 => 'tishenkovld_dudnik_pf2019.pgn/0',
      4 => 'skorikov_tishenkovld_pf2019.pgn/0',
      5 => 'tishenkovld_shelkovskiy_pf2020.pgn/0',
      6 => 'nikolaev_tishenkovld_pf2020.pgn/0',
      7 => 'tishenkovld_oganesyananna_pf2020.pgn/0',
      8 => 'zelyak_tishenkovld_pf2020.pgn/0',
    ),
    'Углев Эдуард' => 
    array (
      0 => 'gulinskiy-uglev_06012018.pgn/0',
      1 => 'uglev_djachenkoserg_2018.pgn/0',
      2 => 'shirinyan_uglev_2018.pgn/0',
      3 => 'uglev_makarov_2018.pgn/0',
      4 => 'uglev_irupin_2018.pgn/0',
      5 => 'telmanov_uglev_2018.pgn/0',
      6 => 'uglev_leonov_2018.pgn/0',
      7 => 'sudnizyn_uglev_2018.pgn/0',
      8 => 'uglev_konoplev_2018.pgn/0',
      9 => 'zobnin_uglev_2018.pgn/0',
      10 => 'rudv_uglev_2018.pgn/0',
      11 => 'grizenko_uglev_2018.pgn/0',
    ),
    'Устинов Александр' => 
    array (
      0 => 'ustinov_kotlyarov_pf2020.pgn/0',
      1 => 'ardashev_ustinov_pf2020.pgn/0',
      2 => 'ustinov_zelyak_pf2020.pgn/0',
      3 => 'oganesyananna_ustinov_pf2020.pgn/0',
      4 => 'ustinov_nikolaev_pf2020.pgn/0',
      5 => 'skorikov_ustinov_pf2020.pgn/0',
      6 => 'ligay_ustinov_pf2020.pgn/0',
    ),
    'Фишер Роберт' => 
    array (
      0 => 'Spassky_Fischer_1972_1.pgn/0',
      1 => 'Spassky_Fischer_1972_21.pgn/0',
    ),
    'Цукерторт Иоганн' => 
    array (
      0 => 'Zukertort_Steinitz_1886_1.pgn/0',
      1 => 'Steinitz_Zukertort_1886_20.pgn/0',
    ),
    'Чигорин Михаил' => 
    array (
      0 => 'Chigorin_Steinitz_1889_1.pgn/0',
      1 => 'Chigorin_Steinitz_1889_17.pgn/0',
      2 => 'Chigorin_Steinitz_1892_1.pgn/0',
      3 => 'Chigorin_Steinitz_1892_23.pgn/0',
    ),
    'Шелковский Артем' => 
    array (
      0 => 'shelkovskiy_tishnkovld_pf2019.pgn/0',
      1 => 'dudnik_shelkovskiy_pf2019.pgn/0',
      2 => 'shelkovskij_irupin_pf2019.pgn/0',
      3 => 'samsonov_shelkovskiy_pf2019.pgn/0',
      4 => 'shelkovskiy_moskalenko_pf2019.pgn/0',
      5 => 'dedikov_shelkovskiy_pf2019.pgn/0',
      6 => 'shelkovski_grechkin_122018.pgn/0',
      7 => 'loktionov_shlkovskiy_pf2020.pgn/0',
      8 => 'tishenkovld_shelkovskiy_pf2020.pgn/0',
      9 => 'shelkovskiy_ligay_pf2020.pgn/0',
      10 => 'ardashev_shelkovskiy_pf2020.pgn/0',
      11 => 'oganesyananna_shelkovskiy_pf2020.pgn/0',
      12 => 'tishenkovik_shelkovskiy_2020.pgn/0',
    ),
    'Ширинян Вазир' => 
    array (
      0 => 'shirinnyan_konoplev_2018.pgn/0',
      1 => 'zobnin_shirinyan_2018.pgn/0',
      2 => 'shirinyan_uglev_2018.pgn/0',
      3 => 'volginalex_shirinyan_2018.pgn/0',
      4 => 'shirinyan_gulinskiy_2018.pgn/0',
    ),
    'Шлехтер Карл' => 
    array (
      0 => 'Schlechter_Lasker_1910_1.pgn/0',
      1 => 'Lasker_Schlechter_1910_10.pgn/0',
    ),
    'Эйве Макс' => 
    array (
      0 => 'Alekhine_Euwe_1935_1.pgn/0',
      1 => 'Euwe_Alekhine_1935_30.pgn/0',
      2 => 'Euwe_Alekhine_1937_1.pgn/0',
      3 => 'Euwe_Alekhine_1937_25.pgn/0',
      4 => 'Euwe_Keres_1948_1.pgn/0',
      5 => 'Botvinnik_Euwe_1948.pgn/0',
    ),
    'Яновский Давид' => 
    array (
      0 => 'Lasker_Janowski_1909_1.pgn/0',
      1 => 'Janowski_Lasker_1909_10.pgn/0',
      2 => 'Lasker_Janowski_1910_1.pgn/0',
      3 => 'Lasker_Janowski_1910_11.pgn/0',
    ),
    'консультанты' => 
    array (
      0 => 'Morphy_Isouard_1858.pgn/0',
    ),
  ),
)